### ISSUE TITLE
NullDC (Dreamcast) - Controllers not working

### ISSUE THREAD

**Issue by Naesala06** [doZennn/steam-rom-manager#250]
Hello,

I wanted to add NullDC on Steam, and I followed the instructions given in the issue "SRM & NullDC (Dreamcast) #110".
Everything is functionnal, except the controllers.
I don't have any issue when I launch the game from the emulator directly. It's only when I launch through steam.

Thank you for your help.

**Comment by cbartondock** [comment]
This is probably not something SRM can fix, assuming you have the same issue if you manually add the shortcut to steam (check this). We are just the middleman, so to speak - we add the shortcut and auto populate artwork. Other than for the Epic Store we don't do anything in the background to change the way the game runs. Probably you need to talk to the NullDC devs.
