### ISSUE TITLE
[Feature Request] Option to omit certain steam accounts from having shortcuts added

### ISSUE THREAD

**Issue by klepp0906** [doZennn/steam-rom-manager#255]
I've gone for some  years with a sole steam account so never even considered this scenario.  I recently created a second and would prefer to have my rom shortcuts only added to one of the two accounts.

Unfortunately as best I can tell SRM picks up both accounts and its all or nothing.  A checkbox next to each account in the parser window before saving would suffice.

I imagine this is extra important for folks that have several people using steam or logging into steam on the same computer.

**Comment by cbartondock** [comment]
You can specify user account(s) within the parser!
