### ISSUE TITLE
yuzu emulator directory wildcard.

### ISSUE THREAD

**Issue by IanGoldense** [doZennn/steam-rom-manager#258]
it would be a nice feature if the program could look for the ROM file inside of individual folders. i like to keep them all in separate folders within the ROM directoy but they will not be parsed correctly if ROMs are stored that way.

**Comment by kencinder** [comment]
It can search however you tell it to, if you look at the info by clicking the green ( i ) beside `user glob` there are examples for this.
In the case of the Yuzu preset, you would change the glob from this...

`${title}@(.kip|.KIP|.nca|.NCA|.nro|.NRO|.nso|.NSO|.nsp|.NSP|.xci|.XCI)`

to `*/${title}@(.kip|.KIP|.nca|.NCA|.nro|.NRO|.nso|.NSO|.nsp|.NSP|.xci|.XCI)` to have SRM pull the title from files inside subdirectories of your ROMs directory.

or to `${title}/*@(.kip|.KIP|.nca|.NCA|.nro|.NRO|.nso|.NSO|.nsp|.NSP|.xci|.XCI)` to have SRM pull the title from the subdirectory names inside your ROMs directory.
