### ISSUE TITLE
[Suggestion] [PS3] Add the --no-gui flag to Sony PlayStation 3 - RPCS3 (Extracted ISO/PSN)

### ISSUE THREAD

**Issue by marat569** [doZennn/steam-rom-manager#259]
So, first off loving this program, picked it up today.

My suggestion is a small tweak to the "Sony PlayStation 3 - RPCS3 (Extracted ISO/PSN)" community profile. I have no idea where to post said requests, but I found this place.

So the default settings of said profile launch both the emulator, and the game; confusing Steam's overlay, and features such as streaming to a friend.

The --no-gui flag makes it launch the game headless, so pressing play/clicking the shortcut feels like opening any other native game.

The change would be to "Command Line Arguments" with the final result being

    --no-gui "${filePath}"

Picture of the parser's settings: https://i.imgur.com/4BqELBN.png

Picture of how a game with --no-gui should look in steam: https://i.imgur.com/btHlAux.png

While this isn't anything crazy, and anybody can fix it on their own with a few google searches; I feel like it would be a nice QoL change. Maybe even add a separate "headless" user profile for those who like having the emulator open alongside the game.

Thanks!

**Comment by kencinder** [comment]
Makes sense, will add `--no-gui` to both RPCS3 presets next time I do a round of updates/additions
