### ISSUE TITLE
Split customVariables.json out into separate files like presets

### ISSUE THREAD

**Issue by kencinder** [doZennn/steam-rom-manager#260]
The customVariables.json is quite large and unwieldy to work with at this point, I propose splitting it out into separate files per variable in the same manner the presets are now.

**Comment by cbartondock** [comment]
@kencinder if you're willing to do the actual splitting up of the file into folders the way you want it then I'll write the code to start pulling from that instead of customVariables.json

**Comment by kencinder** [comment]
Do you want me to just create the files in master or create a new branch?

I envision the following, just like the presets

```
files
  |
  -->customVariables
       |
       ------> Arcade.json
       ------> Sony PlayStation 3.json

**Comment by cbartondock** [comment]
Master is fine, just keep the old file present as well (like we did with presets)

**Comment by kencinder** [comment]
Split everything out into their own files. I opted to completely separate by emulator for arcade, because the resulting file was still huge otherwise thanks to MAME alone, split PS3 into two as well for Disc and PSN

https://github.com/SteamGridDB/steam-rom-manager/tree/master/files/customvariables

**Comment by cbartondock** [comment]
Done in master, will be in the next version.
