### ISSUE TITLE
Dosbox games from GOG Galaxy broken

### ISSUE THREAD

**Issue by hanranti** [doZennn/steam-rom-manager#263]
When Dosbox games are added from GOG target fields quotation marks are wrongly placed and startup folder is wrong but can be easily fixed manually. For example:

The Elder Scrolls: Arena

target:
"C:\GOG\Arena\DOSBOX\dosbox.exe -conf "..\dosbox_arena.conf" -conf "..\dosbox_arena_single.conf" -noconsole -c "exit""

folder:
C:\GOG\Arena\DOSBOX\dosbox.exe -conf "..\dosbox_arena.conf" -conf "..

instead of

target:
"C:\GOG\Arena\DOSBOX\dosbox.exe" -conf "..\dosbox_arena.conf" -conf "..\dosbox_arena_single.conf" -noconsole -c "exit"

folder:
C:\GOG\Arena\DOSBOX\

Also when selecting Launch games via GOG Galaxy the folder section is still the same as without it.

This issue does not exist in for example when adding games with Playnite 8 and https://github.com/bburky/playnite-non-steam-shortcuts instead.

**Comment by cbartondock** [comment]
Thanks for pointing this out! I will look into it.

**Comment by cbartondock** [comment]
Fixed in master.
