### ISSUE TITLE
Epic preset parser Manifests Directory Override not working

### ISSUE THREAD

**Issue by alexlobrano** [doZennn/steam-rom-manager#264]
The Epic preset parser is unable to find any games when using Legendary (and Heroic) with the override field, at least on Win10. The location of the manifests for Legendary seems to be %USERPROFILE%\.config\legendary\manifests, and within there are .manifest files for each installed game. However in SRM the parser returns 0 titles when specifying that directory as the override folder. With all other settings the same but leaving the override folder blank (so it defaults to the Epic manifests folder which has .item files), the parser finds everything correctly.

**Comment by kencinder** [comment]
I do believe this to be a case of the Epic parser only looking for .item files judging by https://github.com/SteamGridDB/steam-rom-manager/blob/e6f5319ec778e7c64d6c6d54a519cea8c1ac0ede/src/lib/parsers/epic.parser.ts#L65

Not truly a bug per-say, as Legendary is doing things differently, but should be fixed.

**Comment by kencinder** [comment]
For now maybe enabling this setting referenced in https://github.com/derrod/legendary/discussions/276#discussioncomment-709748 that supposedly creates the .item files will work until the Epic parser is fixed to handle the way Legendary does it.

**Comment by cbartondock** [comment]
Unless someone wants to create a separate parser for Legendary and submit it as a PR I am just going to say that one needs to enable that setting in the readme for the Epic Parser and call it a day!
