### ISSUE TITLE
[Suggestion] Allow us to pull animated art from SteamGridDB. Posters, Heroes, Logos, Backgrounds, Icons, all of it. 

### ISSUE THREAD

**Issue by HiTech-LoLife** [doZennn/steam-rom-manager#269]
So Steam has support for animated art elements, and SteamGridDB hosts custom animated art of various types for quite a few games. 

My suggestion would be to have Rom Manager pull animated WEBM or APNG files and let us set those as our primary arts. 

In addition to that... I'd also want the ability to filter art by animated and non animated. The attached video file showcases one such an animated art working on Steam Deck as well. 

https://user-images.githubusercontent.com/89883103/156660132-a54760f3-ee38-443c-bc02-320b7daf3c3e.mp4

**Comment by cbartondock** [comment]
Added in 2.3.34
