### ISSUE TITLE
"${exePath}" generates nonfunctional - but correct - "Target" on Steam Deck

### ISSUE THREAD

**Issue by Neofalcontoo** [doZennn/steam-rom-manager#270]
I just got my Steam Deck a few days ago, and after a lot of tinkering trying to get Steam Rom Manager working with the flatpack version of Dolphin, I've identified a bug that prevents Steam Rom Manager from functioning correctly.

In order to have Steam Rom Manager work correctly with the Flatpack version of Dolphin on the Steam deck, the parser must have a "run org.DolphinEmu.dolphin-emu" appended to the "target" line in Steam, and "-b -e "${filePath}" in the "Launch Options" line in Steam.

Setting the parser up to do this (by going into advanced options and un-checking "Append arguments to executable") generates a shortcut in Steam which, when you examine it, **_will be 100% correct._** However, attempting to use it will cause Dolphin to not launch.

Deleting the target line, however, and retyping (manually) the **exact same line** in will cause it to work as it should.

I've never used linux before, and I'm way over my head here, technically, but I found a solution to the problem that leads me to believe the culprit is "${exePath}"

By replacing "${exePath}" with the actual path myself, the shortcut it generates will be exactly the same.... but actually works how it should.

So.... there's something with "${exePath}" causing invalid shortcuts on Steam Deck.

**Comment by kencinder** [comment]
All `"${exePath}"` does in SRM is fill out the path the the executable you have set, which with Flatpak would be `/usr/bin/flatpak`, which can be seen when testing a parser.

Multiple examples on Reddit and the SRM configs provided by [Emudeck](https://github.com/dragoonDorise/EmuDeck/blob/main/configs/steam-rom-manager/userData/userConfigurations.json#L30) seem to work fine for everyone else, without touching `Append Arguments to Executable`
