### ISSUE TITLE
Cemu parser generates incorrect filePaths on SteamDeck

### ISSUE THREAD

**Issue by PineappleIOnic** [doZennn/steam-rom-manager#272]
The Cemu parser will generate the filePath as if Cemu was running directly on Linux however because of Cemu running on proton the path is incorrect as proton emulates a windows file system mounting the normal Linux filesystem on the `z:/` drive.

Maybe there could be a check or a Steamdeck version of this parser that adds the `z:/` prefix to the path?

**Comment by kencinder** [comment]
I've started working on adding presets for the deck(Flatpak), and I have no problem adding non native emulators to the presets for it, but if this is just a case of adding that Z: drive to the path, there is no need for adding presets for something so simple.

If all that is needed is the `Z:/` portion that could easily be added like so: `"Z:/${filePath}"`

**Comment by kencinder** [comment]
I'm going to assume based on my observations reading other things such as posts for this on the Deck on Reddit, that is all that is required.
