### ISSUE TITLE
Steam Parser with titles that are numbers

### ISSUE THREAD

**Issue by bladeSk** [doZennn/steam-rom-manager#278]
When testing the "Steam" community preset parser with a manually entered user account id, the test fails with:

> Testing failed
> TypeError: this.getVariable(...).trim is not a function

I'm using the [latest AppImage](https://github.com/SteamGridDB/steam-rom-manager/releases/download/v2.3.29/Steam-ROM-Manager-2.3.29.AppImage) on a Steam Deck.

**Comment by cbartondock** [comment]
This seems like steam's folder structure might be different on the steam deck? I don't own one so it is difficult for me to check. I will look into it to the extent I can.

**Comment by bladeSk** [comment]
I can send you more details or the folder structure. Just tell me what you need.

**Comment by cbartondock** [comment]
Can you do a CTRL+SHIFT+I or whatever the equivalent is on steam deck to bring up the developer console when this error appears? Curious if there is any additional information on the error there. Not really sure where to start otherwise.

**Comment by bladeSk** [comment]
There's nothing in the console, the exception seems to get caught.

I tried getting the project built directly on Steam Deck, but it fails on node-gyp/sqlite3 because of missing GCC headers and they can't be installed without modifying the system partition.

If you included source maps in the build and logged fatal exceptions to the console, I could tell you why exactly it's failing.

**Comment by cbartondock** [comment]
I just checked on the emu-deck discord with some of the others users there and they are not seeing this issue - so it isn't a directory structure issue, it's something peculiar to your steam games. Out of curiosity do you have a way of testing it with the same steam library on a PC? If the issue still occurs that would confirm my theory and make it easier to debug.

**Comment by bladeSk** [comment]
OK, I'm getting the same issue on my Windows PC, so it has probably something to do with my account. However, I can't get the project to run, not sure how it's supposed to work, but the webpack config is in typescript and it's not readable by Node (`npm run watch:main`, using the latest LTS). Maybe the readme is missing some details regarding this?

**Comment by cbartondock** [comment]
Did you do an `npm ci` to get typescript and everything else installed?

**Comment by bladeSk** [comment]
Sure. To give you more context, the error message says: `[webpack-cli] Failed to load 'D:\_temp\steam-rom-manager-master\webpack\main.js' config`. How is plain Node supposed to load a .ts file? Do you use vanilla Node or some alternate runtime like Deno?

**Comment by cbartondock** [comment]
Look at the build scripts in `package.json`:
```
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "validate-files": "ts-node ./.validate-files.ts",
    "update-files": "ts-node ./.update-files.ts",
    "start": "electron ./dist/main.bundle.js",
    "watch:main": "webpack --watch --config ./webpack/main.js",
    "watch:renderer": "webpack --watch --config ./webpack/renderer.js",
    "prepare:build": "cross-env tsc -P ./webpack",
    "build:main": "cross-env NODE_ENV=production webpack --config ./webpack/main.js",
    "build:renderer": "cross-env NODE_ENV=production webpack --config ./webpack/renderer.js",
    "prebuild:dist": "npm run prepare:build",
    "build:dist": "rimraf dist && npm run build:main && npm run build:renderer",
    "build:win": "electron-builder --win --ia32 --x64",
    "build:linux": "electron-builder --linux --ia32 --x64",
    "build:docker": "electron-builder --linux --win --ia32 --x64 --publish onTagOrDraft",
    "build:mac": "electron-builder --mac --ia32 --x64"
  },
```
So 
```
npm ci; 
npm run build:dist;
npm run start
```
When you do `npm run build:dist` it should automatically run `npm run prebuild:dist` first. So what you are really doing is
```
cross-env tsc -P ./webpack //this compiles the webpack typescript files into JS files
rimraf dist //cleans up the dist folder
cross-env NODE_ENV=production webpack --config ./webpack/main.js //builds the main process
cross-env NODE_ENV=production webpack --config ./webpack/renderer.js //builds the renderer process
electron ./dist/main.bundle.js // runs the main process
```
It seems like maybe `npm run build:dist` isn't automatically calling `npm run prebuild:dist` for some reason on your system? If so all you need to do is `npm run prebuild:dist` first. If that's the case I will point out in the readme that this can occur.

**Comment by cbartondock** [comment]
For the record does it also fail when you don't manually enter your id number, ie when you do `${my_steam_username}`?

**Comment by bladeSk** [comment]
OK, now it makes sense. I didn't run the build script, as I wanted to debug the app, not build it. Running `npm run watch:main` doesn't trigger the prebuild script, which is why the TS config never got transpiled to JS and `npm run watch:main` fails. Now I got it up and running and will let you know what I find.

As for the second question, that's not working at all, my user name is "81403" (ie. all numbers - could this be an issue? 🤔) and specifying `${81403}` results in "Steam directory specified has no accounts.", while using just the ID works.

**Comment by bladeSk** [comment]
So the parser fails right here: https://github.com/SteamGridDB/steam-rom-manager/blob/9f3ced394ea7648532a04cfc644b8492445b5490/src/lib/file-parser.ts#L296

`this.getVariable('title', variableData)` returns `140` in my case, which is a _number_, which doesn't have a trim() method and it fails. Looks like it may have something to do with my account name being a bunch of numbers.

Here's the variableData object.
```
{
    "executableLocation": "242820",
    "extractedTitle": 140,
    "steamDirectory": "D:\\Games\\_Steam",
    "fuzzyTitle": 140,
    "romDirectory": "",
    "steamDirectoryGlobal": "D:\\Games\\_Steam",
    "romsDirectoryGlobal": "",
    "retroarchPath": "",
    "raCoresDirectory": "",
    "localImagesDirectory": ""
}
```

**Comment by cbartondock** [comment]
That seems more like somehow a game's steam appid is being used as it's title. That said you don't happen to have a game that *is* called 140 do you?

**Comment by cbartondock** [comment]
Like say https://store.steampowered.com/app/242820/140/

**Comment by bladeSk** [comment]
Yeah, I actually _do_ have it :)

**Comment by cbartondock** [comment]
Okay I just bought 140 and tried it out, and I am not seeing the same error. But it's possible I have fixed it. What version of SRM are you running?

**Comment by cbartondock** [comment]
It's also possible your original theory about your username being numerical is correct.

**Comment by cbartondock** [comment]
Since 140 is just the first game for which the error would appear, being alphabetically first.

**Comment by bladeSk** [comment]
Just tried the latest version (00d1aa1), experiencing the same issue at the same line. It's indeed related to the game "140", even the executableLocation: "242820" matches the game ID.

Adding this:
```js
if (data[i].success[j].extractedTitle) {
  data[i].success[j].extractedTitle = '' + data[i].success[j].extractedTitle;
}
```          
before this line https://github.com/SteamGridDB/steam-rom-manager/blob/e7dce9f9b921ba3bac30c4e4c04ea118049d0f00/src/lib/file-parser.ts#L214

fixes the issue, but I feel it's more of a hack than a proper fix, because `extractedTitle` arrives as a number from the steam.parser. Maybe `binary-vdf` assumes data type depending on how the data looks - ie. it thinks 140 must be a number. But I'm just taking a guess here and it doesn't explain how come it's working for you and not for me.

**Comment by cbartondock** [comment]
Issue is with @node-steam/vdf I think, and the `screenshots.vdf` file. I created an issue over there, but I am working on a fix in SRM in the meantime. https://github.com/node-steam/vdf/issues/15

**Comment by cbartondock** [comment]
Fixed as of 2.3.33

**Comment by daalta** [comment]
Unfortunately I'm experiencing this issue in 2.3.37. Though it's close to https://github.com/SteamGridDB/steam-rom-manager/issues/284

```
Cannot make changes while Steam while Steam is running!
Fatal error occurred in Preview. See event log for details.
Fatal Preview Error Error: Could not merge entries. TypeError: this.Filedata.shortcuts.push is not a function
```

**Comment by cbartondock** [comment]
This is not the same error, please create a new issue.
