### ISSUE TITLE
Add option to force Steam overlay like with SteamGridDB Manager

### ISSUE THREAD

**Issue by Ericbazinga** [doZennn/steam-rom-manager#281]
Steam ROM Manager supports adding games from other storefronts like Epic and GOG, but lacks some extra code that SteamGridDB uses to force Steam Overlay on when playing a game. Steam Overlay is needed for Steam Controller and (in theory, I don't have mine yet) Steam Deck controllers to properly function. I don't know if this is true, but I heard that SteamGridDB Manager was being deprecated and replaced with Steam ROM Manager. Either way, Steam ROM Manager has most of the same functionality as SteamGridDB and I'd imagine most would want to use just the one tool. I tried using an alternative called [SteamRunner](https://github.com/Lulech23/SteamRunner) but couldn't get it to work at all.

If an option to force Steam overlay on was added, that'd be super helpful. I'd suggest making it an opt-in checkbox so those who need it can turn it on and it doesn't potentially break anything for others. 

Thanks for your consideration!

**Comment by cbartondock** [comment]
This is a good idea, I didn't realize that was a settable option. Will add soon.

**Comment by rkr87** [comment]
This isn't a requirement on the deck as the original poster expected it might be. Overlay is automatically forced when playing in "Game Mode".

**Comment by kana2001** [comment]
I am not 100% sure on how the Steam overlay functions for non-steam games. But having the overlay setting lets steam correctly map the Dualsense and other unsupported controllers (probably). Non-steam games added by Steam ROM Manager does not correctly map the Dualsense. But when I add the non steam game manually, the Dualsense functions and the overlay works.

**Comment by cbartondock** [comment]
this seems to be on by default in the newest versions of steam, so I am going to close this.
