### ISSUE TITLE
[Feature Request] Multiple ROM directories for one parser

### ISSUE THREAD

**Issue by Leseratte10** [doZennn/steam-rom-manager#285]
Would it be possible to add a feature to allow multiple ROM paths to be used for one parser / emulator?

For example, with Dolphin and this config as included in the repository: 

```json
{
	"Nintendo Wii - Dolphin": {
		"parserType": "Glob",
		"configTitle": "Nintendo Wii - Dolphin",
		"steamCategory": "${Wii}",
		"executableModifier": "\"${exePath}\"",
		"romDirectory": "path-to-roms",
		"steamDirectory": "${steamdirglobal}",
		"startInDirectory": "",
```

it seems to only allow one single ROM directory. 

I plan to use this on the Steam Deck and have the ROMs I use most of the time be stored on the internal storage, with the ones I rarely use stored on an additional large SD card. 

It would be great if I could do something like this: 

`"romDirectory": [ "/home/deck/dolphin-roms", "/run/media/mmcblk0p1/dolphin-roms" ]`

and then the Steam ROM manager would create Steam game entries for all ROMs that are either stored on the Steam Deck itself or on the inserted SD card. 
Right now it looks like the only way to do that would be to duplicate the whole "Dolphin" preset which isn't really a good solution imo, as it just makes the file unnecessarily large and results in duplicate config entries.

**Comment by peetezaah** [comment]
Having just upgraded my internal storage, I'm on the same boat.  
I'm guessing this was not implemented. Did you find another solution?

**Comment by cbartondock** [comment]
As a workaround you could just drop symlinks to all the folders you want in a single folder and have srm search it recursively
