### ISSUE TITLE
Ability to search multiple folders per parser.

### ISSUE THREAD

**Issue by Justice-Net** [doZennn/steam-rom-manager#286]
I'm going to apologize in advance as I'm not the best at writing out my issues.

Ok, so I'm trying to upload rom images to steam. Program works fine with the exception of PS1 regarding bin/cue files. To stay organized, all of my PS1 games are each in their own separate folders. Because of this SRM won't show them  since the program only looks in the psx folder and not inside of any folders in that directory.

I've tried pulling the games out of the folders, but for some reason SRM will make images for both the .bin and .cue images.

**Comment by cbartondock** [comment]
This is better a question for the discord support section. If your folder structure is: 

Games
-- game1
---- game1.bin
---- game1.cue
-- game2
---- game2.bin
---- game2.cue

then set `ROMs Directory` to `Games` and set the glob to, for example, `${title}${/}${title}.@(cue|CUE)`

What works will depend on your exact directory structure, so if you're having trouble I recommend the discord.
