### ISSUE TITLE
[feature request] flatpak release

### ISSUE THREAD

**Issue by KP2048** [doZennn/steam-rom-manager#287]
can you put this on flathub?

**Comment by doZennn** [comment]
Dupe #254

**Comment by KP2048** [comment]
Not a dupe not talking about steam flatpak I mean a flatpak of steam rom manager

**Comment by KP2048** [comment]
If I do a pr would you guys consider it?

**Comment by doZennn** [comment]
Sure, some work on a Flatpak version would be sweet.

**Comment by KP2048** [comment]
I’m probably going to set it up to just extract the deb file. Getting electron to build in flatpak is a pain

**Comment by Witherking25** [comment]
[srm-flatpak.zip](https://github.com/SteamGridDB/steam-rom-manager/files/8566410/srm-flatpak.zip)

**Comment by Witherking25** [comment]
that can go on flathub

**Comment by doZennn** [comment]
Has this been tested with all the parsers?

**Comment by KP2048** [comment]
yes

**Comment by doZennn** [comment]
If you're confident with it working, do you mind transferring ownership of the Flathub repo to me?  
I'd prefer to have overall control over the package that way we can have it official. I'll add you as a contributor so you can still make changes.

**Comment by KP2048** [comment]
Sure. Once it is merged

**Comment by KP2048** [comment]
Would I transfer it to SteamGridDB once I can?

**Comment by doZennn** [comment]
Yep

**Comment by KP2048** [comment]
can you merge the pr i just made so that steam rom manager can still parse host executables in a flatpak environment?

**Comment by KP2048** [comment]
- https://github.com/SteamGridDB/steam-rom-manager/pull/288

**Comment by KP2048** [comment]
The flatpak manifest pulls from the GitHub releases so it needs a new release to update it with the patch

**Comment by doZennn** [comment]
https://github.com/SteamGridDB/steam-rom-manager/releases/tag/v2.3.30

**Comment by KP2048** [comment]
Nice

**Comment by KP2048** [comment]
The owner will actually be changed to flathub once that pr is merged. I will get write access and I will give it to you too

**Comment by KP2048** [comment]
unable to transfer ownership bc:
```
 You don’t have the permission to create public repositories on SteamGridDB 
```

**Comment by KP2048** [comment]
I'd rather SteamGridDB be the owner of the fork so that once it gets merged it is the maintainer

**Comment by doZennn** [comment]
Transfer it to me then I'll move it to the SGDB org.

**Comment by KP2048** [comment]
I would still like to keep write access obviously

**Comment by KP2048** [comment]
Request sent

**Comment by KP2048** [comment]
It was on my GitHub org so i had to transfer it to my profile first

**Comment by doZennn** [comment]
Transferred to https://github.com/SteamGridDB/flathub-srm

**Comment by doZennn** [comment]
https://flathub.org/apps/details/com.steamgriddb.steam-rom-manager
