### ISSUE TITLE
[Missing Fuzzy Titles] Tetris (Gameboy), Pokemon Gold Version, Pokemon Sapphire Version

### ISSUE THREAD

**Issue by CheezyFriez12** [doZennn/steam-rom-manager#294]
I have discovered 2 missing titles, those being Tetris (Gameboy) and Pokemon Gold Version.

**Comment by kencinder** [comment]
Title matches with steamgriddb are not the fault of SRM, if a title doesn't exist on steamgriddb then it's something to bring to their attention.

However both of these very much do exist on the site.

https://www.steamgriddb.com/game/5249689

https://www.steamgriddb.com/game/36203

**Comment by a8bit** [comment]
Sorry for the necro bump here but I hit this issue today. It's not that the title "Tetris (Gameboy)" doesn't exist, it's that SRM can't find it when fuzzy matching. 

My file is called "Tetris (World) (Rev1).gb", giving me a title of "Tetris". I guess it could be "Tetris " if the removal of diacritics and parenthesis is not also stripping any leading/trailing whitespace. 

When searching the SteamGridDB for "Tetris" it returns "Tetris 2", it looks like thats the first available match for Tetris that was available for the Gameboy. It seems like the match routine is not doing the same name modifications to titles in the DB so "Tetris" never matches "Tetris (Gameboy)" which is how it's stored in SteamGridDB

The Tetris project on SteamGridDB is doing the "(_Platform_)" thing with a lot of Tetris titles and this is going to make matching them with the games on Stream impossible.

**Comment by kencinder** [comment]
This still isn't an SRM issue, there's no way for SRM to know your game is platform specific. SRM doesn't know or care what a file is, you could parse TXT files or movies with SRM if you wanted to.

An override can however be used in SRM to match a title, to the correct entry on SGDB in any case where the resulting match provided isn't correct.
