### ISSUE TITLE
"Fatal preview error error" when saving app list on Steam Deck

### ISSUE THREAD

**Issue by crscaballero** [doZennn/steam-rom-manager#304]
I've been using this app for a while on my Steam Deck and sometimes when I'm importing new games I'm getting the error

```
Populating VDF list.
Creating backups.
Reading VDF files.
Merging VDF entries.
Saving added category information to localconfig.vdf
Non-fatal error(-s) occurred while saving VDF/image files.
Fatal error occurred in Preview. See event log for details.
Fatal Preview Error Error: 





```

whit a lot of empty lines under the `Fatal Preview Error Error: ` without saying which was the error, I've tried removing the last added games, using ones which were working before and the same issue happening again without sating which was the actual error

SRM version: 2.3.36
Operating System: Linux 5.13

**Comment by cbartondock** [comment]
I think the issue here is steamgriddb timing out for large images. I will extend the timeout in the next build and we'll see if the issue persists. If you hit CTRL+SHIFT+I and go to the console in SRM you might get more insight into the error.

**Comment by mistercasualMST** [comment]
I came here to report the same error. Console shows: Failed to load resource: net ::ERR_INSUFFICIENT_RESOURCES trying to reach pngs at cd2.steamgriddb.com

**Comment by cbartondock** [comment]
@mistercasualMST how many images are you attempting to pull? I think electron has a limit, we may need to do some batching

**Comment by mistercasualMST** [comment]
Yup, that makes perfect sense. I was overzealously working through around 3,600 titles.

**Comment by cbartondock** [comment]
Ah yeah that is a lot. Just to be sure you should try going parser by parser and see if that fixes it.

**Comment by cbartondock** [comment]
I actually think it has to do with the limit on the number of files posix systems allow you to work with
![Screenshot 2022-05-16 180640](https://user-images.githubusercontent.com/4482454/168691536-56551ab8-6280-4b09-b2d9-9d237436c65b.png)
So potentially an easy fix.

**Comment by cbartondock** [comment]
This should be fixed after recent changes to SGDB timeout handling and batching.
