### ISSUE TITLE
Steam Parser Failed

### ISSUE THREAD

**Issue by trowgundam** [doZennn/steam-rom-manager#306]
So, I've been having this issue on two different computers. On one computer, my Desktop, I've always had this issue. On the other computer, my Laptop, it originally worked, but after a reinstall of Window it is giving me the same issue. When trying to test the Steam Parser I get the following:
```
Testing "Steam" parser (SRM version - 2.3.37 Non-Portable).
Operating system is "Windows 11"
Testing failed
Error: File Parser Execution:
 > Steam parser failed with fatal error:
 > Steam changed internal database structure or parser tried to read an outdated database.
Problematic file: C:\Program Files (x86)\Steam\userdata\STEAMID\7\remote\sharedconfig.vdf
Full error:
 Incorrect Key Possibilities: apps
```

All I did was add a new parser using the Steam Community preset. My Steam directory is set in settings, so that is left default, and I filled in my User Account. I tried both the actual name and my Steam ID, but it makes no difference. I tried looking through the issues, but all there is is an old issue that said the problem was fixed in 2.3.4, but I'm on the latest, 2.3.37 (on both machines).

**Comment by cbartondock** [comment]
Can you join the discord and DM me the file in question? I am lontanadascienza on the discord.

**Comment by cbartondock** [comment]
Add your steam games to a category. This limitation is described in built in docs in SRM.
