### ISSUE TITLE
Parser can't create a new working shortcut.

### ISSUE THREAD

**Issue by beltet** [doZennn/steam-rom-manager#309]
Hi.
First off. I don't know how to reproduce this problem. So it's hard to let you know whats wrong.
But it's two people (me and another) that had this problem @ Emudecks discord, subchannel CEMU.

When we try to generate new shortcuts(in my case for CEMU, the emulator) they can't be used in Steam. Neither in Desktop mode or game mode on the deck.

All the configuration for the parser seems right. Target and where to start is right.
Manually created shortcut with the same data works.

Is there any debug output that tells me what files is created? As I think there is some data that is not overwritten and is lingering.
So if I know what files is created I can test deleting those and see if problem still exist.
I have tried to delete shortcuts.vdf to no avail.

Sincerely!

**Comment by rkr87** [comment]
Provide example of shortcut.

**Comment by beltet** [comment]
Here is an example:
https://media.discordapp.net/attachments/968301540924358736/976512219166687242/PXL_20220518_155000110.jpg?width=551&height=735
Excuse the potato...

I have tested with renaming different vdf files to see if that helps.
I have removed and remade the shortcuts several times. 
Tried manually edit the shortcut from "known good" target and start location.
Also manually make a new shortcut, edit it as the non working shortcut. And that works.
Tried reinstall EMUDECK, and cemu start script.
Been in contact with "lontana" on discord and explaining the issue. I asked if this ticket should be kept, and "lontana' recommended it.

**Comment by cbartondock** [comment]
Lontana is me. You fixed the issue right? But we don't know what happened?

**Comment by beltet** [comment]
> Lontana is me. You fixed the issue right? But we don't know what happened?

No sry, I did not fix it... I ended up reimage the device. 
So i don't know what caused it. Will report back if I stumble upon it again.

**Comment by cbartondock** [comment]
Okay, I'll re-open the issue if it crops up again.
