### ISSUE TITLE
Add the ability to rescale downloaded images

### ISSUE THREAD

**Issue by rkr87** [doZennn/steam-rom-manager#314]
It would be handy if we could set options to resize images downloaded from SteamGridDB, ideally we'd set a desired width or height for the image and then SRM would resize the image to meet that requirement while maintaining the aspect ratio of the original image.

EG with a desired width of 400 pixels, SRM would resize the example image dimensions as follows;
800x1200 -> 400x600
400x600 -> 400x600
1200x1800 -> 400x600

This is less of an issue for cover art but for banner and hero art some of the images downloaded are ridiculously large in dimension to the point the art I have downloaded is much larger in filesize than the roms they're for (my images folder in Steam is approaching 4gb).

**Comment by cbartondock** [comment]
I think what I will do is just expose the sizes part of the sgdb api that filters by size - having srm rescale thousands of images on the fly is a bit much. There are also tools / scripts that can go over a whole directory and compress / resize images. It's probably a one liner in bash if image Magick is installed

**Comment by rkr87** [comment]
Yeah, ImageMagick is how I'm currently doing it - maybe adding the ability to execute a shell script after the library import has completed would cover it? I'm trying to get to the point where I can just have SRM handle everything rather than me going through multiple tools/scripts one at a time.

My issue with the size filters on SGDB is that the better artwork doesn't always have lower resolution versions.

One other thought on this, Steam Deck users aren't able to install ImageMagick without removing read-only from the file system, I personally feel comfortable doing this but not sure how confident others would be, having the re-scaling built into SRM would alleviate that concern.

**Comment by cbartondock** [comment]
Might be better off as an sgdb feature in the end - having the server automatically create and store lower res versions of higher res artworks. Then the api request option would be fine. But obviously comes with the cost of extra storage.

**Comment by cbartondock** [comment]
Closing as I am not going to implement this. Probably needs to happen before SRM (at SGDB level) or after (some post-processing tool on the images directory).
