### ISSUE TITLE
Depressurizer like categorisation of Non-Steam Games

### ISSUE THREAD

**Issue by rkr87** [doZennn/steam-rom-manager#315]
I use [Depressurizer](https://github.com/Depressurizer/Depressurizer#:~:text=Depressurizer%20is%20a%20program%20aimed,that%20games'%20Steam%20store%20pages.) to categorise my Steam games based on multiple criteria (Community Rating and Genre are the items I'm most interested in) but it doesn't work for non-Steam games. I don't think that project is maintained so I doubt a request for enhancement would be completed there.

It would be good if SRM could do a similar thing for non-Steam games by identifying the Steam ID of Non-Steam Games in its library. I have a significant number of games on GOG and Epic that exist on Steam but can't categorise easily at the moment.

**Comment by cbartondock** [comment]
Where would srm pull the data from about rating and genre? It is different for every third party store.

**Comment by rkr87** [comment]
I was thinking Steam the same way Depressurizer does? SRM would need to identify the Steam ID of the non-Steam game and then use the Steam API to pull that information. I'm not sure on the details of exactly how Depressurizer does it.

But I know it can pull that information from Steam for games I don't own on Steam - it just can't apply it to non-Steam games.

**Comment by cbartondock** [comment]
It could try, but it's going to be imperfect. I think SGDB might be working on an API that gets games using other app stores ids, in which case it might be able to convert between them. Anyway this is a back burner feature for sure, but I will leave the issue so that I will get around to it in the future. Or someone can submit a PR.

**Comment by rkr87** [comment]
I'd be tempted to try as someone with some minor dev experience but it seems like it could be quite the undertaking and I've only ever really used JAVA/Kotlin in the past.

I know the Lutris API does contain various store IDs for a search by game name - that might be a place to start.

https://lutris.net/api/games?format=json&search=into+the+breach

`            "provider_games": [
                {
                    "name": "Into the Breach",
                    "slug": "2004253604",
                    "service": "gog"
                },
                {
                    "name": "Into the Breach",
                    "slug": "590380",
                    "service": "steam"
                },
                {
                    "name": "Into the Breach",
                    "slug": "27117",
                    "service": "igdb"
                }
            ]`

EDIT: Another thought, IGDB might be the place to get this info rather than Steam - IGDB contains community ratings and genre information for ROMs as well as Steam games so would be able to apply it consistently across the entire SRM library. Lutris also seems to contain the IGDB IDs for roms too.

**Comment by cbartondock** [comment]
I've decided this is way outside SRM's scope so I am going to close this.
