### ISSUE TITLE
Keep getting error when pressing save app list. "this.fileData.shortcuts.push is not a function"

### ISSUE THREAD

**Issue by ghost** [doZennn/steam-rom-manager#317]
Running Manjaro KDE, Steam as a flatpak, and attampted to use use SRM as a flatpak, aur, and appimage. Keep getting error when pressing Save App List. Steam is not running.

`Populating VDF list.`
`Creating backups.`
`Reading VDF files.`
`Merging VDF entries.`
`Cannot make changes while steam is running!`
`Fatal error occurred in Preview. See event log for details.`
`Fatal Preview Error Error: Could not merge entries. TypeError: this.fileData.shortcuts.push is not a function`

**Comment by ghost** [comment]
So I tried to use it on the steam-manjaro version (the version that comes preinstalled) and it still doesn't work

**Comment by cbartondock** [comment]
Closing as duplicate of https://github.com/SteamGridDB/steam-rom-manager/issues/284
