### ISSUE TITLE
TeknoParrot Preset and customVariables 

### ISSUE THREAD

**Issue by natemac** [doZennn/steam-rom-manager#324]
Sorry, I'm not to familiar with how GitHub works, but attached are a Preset and custom Variables for TeknoParrot Emulation.
Preset: https://pastebin.com/NuY9j7t6
Variable: https://pastebin.com/RCZfaLqJ

**Comment by cbartondock** [comment]
@kencinder You got this one?

**Comment by kencinder** [comment]
No, I'm dealing with real life issues and probably won't be available for months

**Comment by cbartondock** [comment]
Okay no worries !

Chris

**Comment by Immersion95** [comment]
This works flawlessly, I can do the PR if it's accepted ?

**Comment by kencinder** [comment]
Done in https://github.com/SteamGridDB/steam-rom-manager/commit/0665418b84408ef76c6d0149e1c9c28c788448a3 and https://github.com/SteamGridDB/steam-rom-manager/commit/aeb6e7a4bf1c7a6d26089899e49cd9cfb8e9d48c
