### ISSUE TITLE
Ignore certain files with the same format as the ones I'm looking for

### ISSUE THREAD

**Issue by DFelten** [doZennn/steam-rom-manager#325]
With the steam rom manager on Windows, whats the best solution to ignore specific files? 

For example, I try to add the Epilogue Operator with the exe file `Operator.exe`. But in the same folder there is a `unins000.exe`. So when searching in the folder, both exe are found. But the `unins000.exe` should be ignored.

I have tried to ignore them with the help of the Users glob. The problem here is, that I have to add `${title}`. So I'm not sure how to use regex here for my problem. I know how to ignore certain file types, but not certain files with the same format as the ones I am looking for.

What is the best way to ignore certain exe files?

**Comment by cbartondock** [comment]
Use a directory of shortcuts (.lnk files in windows .desktop in linux) and use the non steam shortcut preset, or use the manual parser and make a json file specifying the location of exe's. 

SRM is mostly for adding ROMS, but the two workarounds I mentioned were put in place specifically for this type of thing.
