### ISSUE TITLE
Artwork / Images that are chosen in parser are not used in Steam

### ISSUE THREAD

**Issue by dotbanana** [doZennn/steam-rom-manager#328]
I have used Emudeck which comes with Steam Rom Manager. 
When doing the Parsing/Preview i can change the Images of the stuff fine. It shows good in 
Steam Rom Manager. But not in Steam. In Steam it somehow only works on Startpage in 
Recently Played Games. There he shows the right image. But not in library. 

![steambug](https://user-images.githubusercontent.com/22258372/174418150-9b90972e-3efe-4f10-90ac-e2fbbd32b100.png)

**Comment by cbartondock** [comment]
I am totally unable to reproduce this issue, however I notice your steam library is in german. Perhaps steam uses a different data structure in different regions for some incomprehensible reason. Please submit a bug report at https://logs.jozen.blue/ and include your VDFs. DM me the report id on discord, I am lontanadascienza.

**Comment by dotbanana** [comment]
Couple months later and after doing an update this still doesn't work unfortunately.   
I have no idea how to report bugs at this link. There just opens some console for me. And i also do not know what is an VDF and where to find it. I can make more screenshots if anybody needs but other than that i would need a more in detail tutorial that exactly shows what to do where. Sorry

**Comment by hejfelix** [comment]
Same. It always shows the first image in my library regardless of which image I select in the preview.

**Comment by cbartondock** [comment]
@dotbanana you submit a bug report there from within SRM, on the logs pane.

**Comment by cbartondock** [comment]
This should be fixed now. Can you confirm?

**Comment by cbartondock** [comment]
Closing for lack of comment.
