### ISSUE TITLE
Avoid deletion of other custom Steam shortcuts

### ISSUE THREAD

**Issue by gabrieleancora** [doZennn/steam-rom-manager#330]
Hi, 
whenever I use the steam rom manager I always find that it deletes any non steam game that was added to steam without using SRM.
Is it possible to avoid that? So that when I use steam rom manager I can also keep any other custom shortcut, so for example I could open Plex using steam big picture.

I'm not very familiar with typescript but I could look into the code if you need a hand

**Comment by cbartondock** [comment]
That's odd. This is not the intended behavior. Possibly a recent regression, I will look into it.

**Comment by cbartondock** [comment]
I am unable to reproduce this issue having tried a few different configurations. Would you mind submitting a bug report over at https://logs.jozen.blue/? Message me on Discord with the report ID, I am lontanadascienza over there.
