### ISSUE TITLE
ROM Manager forgets assigned images between launches

### ISSUE THREAD

**Issue by SamusAranX** [doZennn/steam-rom-manager#331]
I have a mid-sized library with a bunch of games that I had to manually input images for because the automatic image search failed in one way or another. This is fine, whatever. What's annoying is that almost every time I add a game and open the manager to regenerate the library entries, it forgets about the custom images and resets them to whatever its crummy autodetection thinks the games are.

*Please* find a way to keep image selection consistent between launches. This is incredibly frustrating.

**Comment by stonie08** [comment]
I think this could be solved with what I asked for in #329 combined with a file-naming pattern in the parser (the latter already exists), or at least would be one major use case for it

**Comment by cbartondock** [comment]
Go into SRM settings and enable "prefer steam images by default". This option is the default, so not sure how it got unset.

**Comment by SamusAranX** [comment]
That setting is enabled and was indeed enabled by default, but it's not the solution to my problem as the app still regularly forgets previously set images.

**Comment by cbartondock** [comment]
It will forget the images if the paths to the games change or their titles change, because that changes the appids (which is how the images are stored/remembered). But if you don't continually move your games around / rename them the option I mentioned earlier will always work.

**Comment by cbartondock** [comment]
New feature in master should help with this also, ability to export and import image choices.
