### ISSUE TITLE
SRM does not remove underscores from final name

### ISSUE THREAD

**Issue by ryz** [doZennn/steam-rom-manager#332]
Hello, how do I remove underscores from a game's final title and replace it with whitespaces?

I have my whole game library formatted with underscores instead of spaces. Games show up in Steam with underscores, this creates various issues with sorting/searching for titles.

Example:
```
[1/1]:      Extracted title - Disgaea_Hour_of_Darkness_PS2_(USA)
[1/1]:          Fuzzy title - Disgaea_Hour_of_Darkness_PS2_(USA)
[1/1]:          Final title - Disgaea_Hour_of_Darkness_PS2_(USA)
```

I want the final title to be

`Disgaea Hour of Darkness PS2 (USA)`

How can I achieve this? Thanks.

Edit:
I think I understand what happens a bit better. the fuzzy matcher is thrown off by the "PS2" in the filename and therefore does not match. Can i instruct SRM to ignore the "PS2" characters in `${title}`?

**Comment by cbartondock** [comment]
This kind of "how to" question really belongs in the Discord. You could use the exception manager, for one thing.

**Comment by ryz** [comment]
I've asked this question two times in various channels and didn't get an answer.
