### ISSUE TITLE
Scraper and SteamGridDB rely on U.S. game titles only

### ISSUE THREAD

**Issue by mikelandzelo173** [doZennn/steam-rom-manager#334]
So I've been using EmuDeck for a day now and basically, I have one big problem with scraping in the Steam Rom Manager. From what I could understand so far, it scrapes games by filename. But there is no way to tell SRM that the scraped game is a different one. Emulation Station, for example, lets you select a specific game from the scraping results if you wish to.

In my case, it scraped Mario Smash Football (Super Mario Strikers) as Mario Power Tennis and the Project Zero (Fatal Frame) games failed to scrape completely. I understand, that these games have different names in the U.S. but renaming everything like it's supposed to be named in the U.S. can't be the best solution. Think of PAL romsets.

It was brought to my attention that I could use exceptions for this. But they are very unintuitive to use and require a lot of menu-hopping between the game lists and the exceptions list. Maybe add a right-click event on the scraped games themselves which opens a popup that is already pre-filled with data and you just have to fill in the new title and it adds it automatically to this exception list? That would at least eliminate the constant clicking through the menus to correct everything when there are a lot of errors.

But the best solution would, of course, be to add international game names to the SteamGridDB which should eliminate this problem altogether.

**Comment by cbartondock** [comment]
I will keep this in mind, but as you say this is the exact purpose of the exceptions manager, which can do much more than just change the search title. It can change arguments for specific games, set the search title and the display title independently, and exclude titles.

SRM is a tool for power users, to do things in bulk. The exception manager pretty much covers it. It's really pretty simple once you use it a few times.

Anyway I'll keep the UI suggestion in mind, but I am closing this issue.
