### ISSUE TITLE
image providers option re-enables itself

### ISSUE THREAD

**Issue by klepp0906** [doZennn/steam-rom-manager#336]
It seems (at least with 2.3.39) the image providers option when unchecked to set to "none" will revert itself to SteamGridDB if you leave the parser to preview or settings etc, then come back.

this has forced me to do some sort of convoluted dance of setting it to none, disabling it, going to settings removing everything and clearing cache's, turning on offline mode, and re running in order to get unmolested titles in steam relative to my local shortcuts.

my use case is purely local images, at least at current.  as such I parse a list of shortcuts i named which are named identically to matched artwork and "used to" result in identical names in steam.

I've been on hiatus for some time and a ton has changed for the better with SRM.   this has me hung up though, trying to understand the behavior and why its doing what  its doing.  could be user error, could be a bug, could be both.

For starters I dont want all the colons and trademark symbols etc which could only be coming from steamgridDB, so turning that image provider off in my parser should stop that no?  If so, then the only problem is the fact that disabling it doesnt seem to stick.

Another issue its creating even if i could get past the altering of my shortcut names is a specific title its picking up incorrectly.  Doom (the 2016 version).   Its matching it to a 2019 title called DoomAI and as such thats the title i get in steam.   Would create even larger issues if i werent using local artwork as then it would be giving me the incorrect art as well i assume.

This of course could be addressed with an exception/override but id prefer to address the automagic re-enabling of SGDB if that is in fact whats causing this.  If not, it probably still should be addressed but that means i'm misunderstanding the functionality. 

EDIT: the parser itself may be corrupt.  I used a preset for non-steam shortcuts and mirrored the settings 1:1 outside of category name (which id think would have no bearing) and it pulled no images from SGDB whatsoever when set to.  may be related.   

will close this once i can sort it out and post back/see whats what.

**Comment by klepp0906** [comment]
okay, so it seems the whole shebang is likely related and tied to the following.

just like the original post about it "re-enabling" the setting is somehow becoming unsynced from the file its written to.  My image providers setting said SteamGridDB yet it would pull no images.  just like the inverse when i moved it to none and left and came back, it would re enable.

I had to change it then save, then change it back and save again to get it functioning as its supposed to.

**Comment by klepp0906** [comment]
okay, i lied.  throwing my hands up on this one.  

Image providers being enabled or disabled is essentially tantamount to enabling/disabling SGDB yes?  So not only should it not pull images, but it should not do any funky name altering correct?

It seems at minimum theres a visual bug going on here.   I cannot disable SGDB on a per parser basis.  It re-enables itself (at least aesthetically) and then I have to toggle it off and save it once or twice to get it to stop pulling down/start pulling down images.

what im trying to accomplish is "not" enabling offline mode, "not" disabling SGDB globally, but disabling SGDB on a per parser basis to not only prevent pulling images, but prevent modifications of naming (aka Dolphin becomes Dolphin Up) for example.

**Comment by cbartondock** [comment]
Fixed in 2.3.47
