### ISSUE TITLE
[Feature Request] Sorting of exceptions

### ISSUE THREAD

**Issue by klepp0906** [doZennn/steam-rom-manager#343]
Would very much appreciate a means to sort exceptions.  I imagine it would function like parsers with an up/down arrow.   If you organize things alphabetically for example, should you need to remove one or remove one by accident, then re-adding it requires quite the shuffle depending on how many you use.

**Comment by cbartondock** [comment]
Added in master (sort by date added, alphabetical by old title, alphabetical by new title)
