### ISSUE TITLE
Look and Feel

### ISSUE THREAD

**Issue by joaopauloalbq** [doZennn/steam-rom-manager#345]
Steam-rom-manager looks out of place on SteamOS (and macOS probably).

I think it would be interesting to use the system's native widgets and just change the color scheme to black and green.

I found [nodegui](https://github.com/nodegui/nodegui) which uses the SteamOS native toolkit (Qt). 

Other advantages: low CPU and memory usage.

_I'm not a TypeScript or Qt developer and I don't know if it's viable though 😅_

**Comment by cbartondock** [comment]
No sorry, I definitely won't be doing this. I use SRM on mac and I think it looks fine, but the main issue is that SRM is currently fully cross platform. It requires zero extra work for me to push an update to all three OS families: as an electron app with relatively few native libraries it compiles and runs beautifully on Linux, Windows, and MacOS. If I did this then it would take a bunch of extra work in the future to keep the Mac OS version up to date with the Windows and Linux versions.

I don't think we should risk making MacOS SRM fall behind the Windows and Linux versions just to make it look less out of place.

**Comment by joaopauloalbq** [comment]
I believe that nodegui is fully cross platform and requires zero extra work to push an update in the future to all three OS families with native widgets on all of them. The extra work is to port from Electron to Nodegui. 

Anyway thanks for listening

**Comment by joaopauloalbq** [comment]
Using the native system bar on Linux would already fix the window shadow and title bar buttons.
