### ISSUE TITLE
[Quality Improvement] Show only one entry for multiple-disc games

### ISSUE THREAD

**Issue by OdinVex** [doZennn/steam-rom-manager#348]
Steam Rom Manager detects multiple-disc games and adds entries for each individual disc. Perhaps this can be worked around in a universal way. Example for PSX games (and file names):

```
AIR COMBAT [SLUS-00001]
WING COMMANDER III - HEART OF THE TIGER [1-4] [SLUS-00019]
WING COMMANDER III - HEART OF THE TIGER [2-4] [SLUS-00134]
WING COMMANDER III - HEART OF THE TIGER [3-4] [SLUS-00135]
WING COMMANDER III - HEART OF THE TIGER [4-4] [SLUS-00136]
```

This example would show 5 games instead of just 2.

Edit: A `Final Title` list would have `['AIR COMBAT', 'WING COMMANDER III - HEART OF THE TIGER', 'WING COMMANDER III - HEART OF THE TIGER', 'WING COMMANDER III - HEART OF THE TIGER', 'WING COMMANDER III - HEART OF THE TIGER', 'WING COMMANDER III - HEART OF THE TIGER']`. If after parsing you can detect whether a title appears in the finalized list multiple times, perhaps some dialogues to specify which one (with file name and Disc ID shown?) might be easiest to differentiate.

**Comment by missionfloyd** [comment]
The solution to this (for emulators that support it, anyway) is to move them into their own folder and make a playlist.

```
WING COMMANDER III - HEART OF THE TIGER [SLUS-00019].m3u
WING COMMANDER III - HEART OF THE TIGER [SLUS-00019]/
├ WING COMMANDER III - HEART OF THE TIGER [1-4] [SLUS-00019].iso
├ WING COMMANDER III - HEART OF THE TIGER [2-4] [SLUS-00134].iso
├ WING COMMANDER III - HEART OF THE TIGER [3-4] [SLUS-00135].iso
└ WING COMMANDER III - HEART OF THE TIGER [4-4] [SLUS-00136].iso
```

Contents of `WING COMMANDER III - HEART OF THE TIGER [SLUS-00019].m3u`:
```
./WING COMMANDER III - HEART OF THE TIGER [SLUS-00019]/WING COMMANDER III - HEART OF THE TIGER [1-4] [SLUS-00019].iso
./WING COMMANDER III - HEART OF THE TIGER [SLUS-00019]/WING COMMANDER III - HEART OF THE TIGER [2-4] [SLUS-00134].iso
./WING COMMANDER III - HEART OF THE TIGER [SLUS-00019]/WING COMMANDER III - HEART OF THE TIGER [3-4] [SLUS-00135].iso
./WING COMMANDER III - HEART OF THE TIGER [SLUS-00019]/WING COMMANDER III - HEART OF THE TIGER [4-4] [SLUS-00136].iso

```
