### ISSUE TITLE
Excessive DNS queries

### ISSUE THREAD

**Issue by bnmoore** [doZennn/steam-rom-manager#349]
I'm new to Steam ROM Manager, but I noticed that when I ran it there were thousands of DNS queries to [www.steamgriddb.com].  I have Pi-hole running on my network and it flagged this and blocked further queries. Is there any way to cache the DNS query result for a few minutes? My personal issue was easy to fix by just disabling the limit in pi-hole, but maybe caching the DNS will improve overall performance and prevent this issue for others in the future?

**Comment by cbartondock** [comment]
Good idea

**Comment by cbartondock** [comment]
Effectively fixed by image download batching in 2.4.0
