### ISSUE TITLE
Add a way to update a category without re-parsing everything that was already in there

### ISSUE THREAD

**Issue by Nutcasey** [doZennn/steam-rom-manager#354]
At the moment if I add a new rom into the snes folder or the like, I can't seem to update it without all the art getting pulled for pre-existing games that were already in the folder. I'd love a way to just update a category and toggle the art just for newly found games.

**Comment by cbartondock** [comment]
I am not going to add this, sorry. SRM is for bulk adding stuff, not for making constant changes.
