### ISSUE TITLE
Change/Add Sega Saturn Emulators to Mednafen /Mednaffe/Beetle Saturn

### ISSUE THREAD

**Issue by effcol** [doZennn/steam-rom-manager#356]
Many games are poorly or completly unsupported in the Sega Saturn emulator SRM uses, Yabause.

To solve this, it would be ideal if you could add [Mednafen](https://mednafen.github.io/) to the app as well, so games could be better supported, or even just switch emulators to Mednafen outright.

Alternatively, there is [Mednaffe](https://github.com/AmatCoder/mednaffe), which is Mednafen but with a GUI to make things easier to change for users. This would be the preferable choice.

Or alternatively, if you wish to still used a RetroArch emulator, you could use [Beetle Saturn](https://docs.libretro.com/library/beetle_saturn/), which is essentially Mednafen but repackaged and renamed for RetroArch, but it would be much preferable to just use Mednaffe.

Incidentally, EmuDeck auto-installs Mednaffe along with Steam Rom Manager, anticipating you'll likly want to use this emulator over Yabause.

**Comment by missionfloyd** [comment]
Here's what I have. The commands this generates work when entered in the terminal, but for some reason don't work when run with Steam. This seems to be the case for many flatpak apps.
<details>
<summary>Sega Saturn - Mednaffe(Flatpak)</summary>

```
# Parser type
····Selected: Glob
# Configuration title
····Sega Saturn - Mednaffe(Flatpak)
# Steam category
····${Saturn}
# Steam directory
····${steamdirglobal}
# User accounts
····
····[x]: Skip found accounts with missing data directories
····[x]: Use account credentials
# ROMs directory
····/home/deck/Roms/Saturn
# Executable
····/usr/bin/flatpak
····[ ]: Follow .lnk or .desktop to destination (Windows and Linux only)
····[x]: Append arguments to executable
# Command line arguments
····run --command=mednafen com.github.AmatCoder.mednaffe "${filePath}"
# Executable modifier
····"${exePath}"
# "Start In" directory
····
# User's glob
····**/${title}@(.ccd|.CCD|.cue|.CUE|.m3u|.M3U|.toc|.TOC)
# User's glob-regex
····null
# Manifests Directory
····null
# Amazon Games Path Override
····null
····[ ]: Launch games via Amazon Games
# Manifests Directory Override
····null
····[ ]: Launch games via Epic for online services
# Galaxy Path Override
····null
····[ ]: Launch games via GOG Galaxy
# itch.io AppData Path Override
····null
# Uplay Directory Override
····null
····[ ]: Launch games via UPlay for online services
# Title from custom variable
····
····[ ]: Case-insensitive variables
····[ ]: Skip file if variable was not found
····[ ]: Enable Title from Custom Variable
# Title modifier
····${fuzzyTitle}
# Fuzzy matching
····[x]: Replace diacritic characters
····[x]: Aggressive matching
····[x]: Remove (...) and [...] brackets
# Image providers
····Selected: SteamGridDB
····[ ]: Allow NSFW artwork
····[ ]: Allow joke artwork
# Allowed grid styles
····Selected: 
# Allowed hero styles
····Selected: 
# Allowed logo styles
····Selected: 
# Allowed icon styles
····Selected: 
# Allowed animation types
····Selected: static
# Online image query
····${${fuzzyTitle}}
# Image pool
····${fuzzyTitle}
# Default image
····
# Default tall image
····
# Default hero image
····
# Default logo image
····
# Default icon
····
# Local images
····
# Local tall images
····
# Local hero images
····
# Local logo images
····
# Local icons
····
```
</details>

This one works with standalone [Mednafen 1.29.0](https://mednafen.github.io/releases/), compiled from source on WSL Debian.

<details>
<summary>Sega Saturn - Mednafen</summary>

```
# Parser type
····Selected: Glob
# Configuration title
····Sega Saturn - Mednaffe(Flatpak)
# Steam category
····${Saturn}
# Steam directory
····${steamdirglobal}
# User accounts
····
····[x]: Skip found accounts with missing data directories
····[x]: Use account credentials
# ROMs directory
····/home/deck/Roms/Saturn
# Executable
····/path/to/mednafen
····[ ]: Follow .lnk or .desktop to destination (Windows and Linux only)
····[x]: Append arguments to executable
# Command line arguments
····"${filePath}"
# Executable modifier
····"${exePath}"
# "Start In" directory
····
# User's glob
····**/${title}@(.ccd|.CCD|.cue|.CUE|.m3u|.M3U|.toc|.TOC)
# User's glob-regex
····null
# Manifests Directory
····null
# Amazon Games Path Override
····null
····[ ]: Launch games via Amazon Games
# Manifests Directory Override
····null
····[ ]: Launch games via Epic for online services
# Galaxy Path Override
····null
····[ ]: Launch games via GOG Galaxy
# itch.io AppData Path Override
····null
# Uplay Directory Override
····null
····[ ]: Launch games via UPlay for online services
# Title from custom variable
····
····[ ]: Case-insensitive variables
····[ ]: Skip file if variable was not found
····[ ]: Enable Title from Custom Variable
# Title modifier
····${fuzzyTitle}
# Fuzzy matching
····[x]: Replace diacritic characters
····[x]: Aggressive matching
····[x]: Remove (...) and [...] brackets
# Image providers
····Selected: SteamGridDB
····[ ]: Allow NSFW artwork
····[ ]: Allow joke artwork
# Allowed grid styles
····Selected: 
# Allowed hero styles
····Selected: 
# Allowed logo styles
····Selected: 
# Allowed icon styles
····Selected: 
# Allowed animation types
····Selected: static
# Online image query
····${${fuzzyTitle}}
# Image pool
····${fuzzyTitle}
# Default image
····
# Default tall image
····
# Default hero image
····
# Default logo image
····
# Default icon
····
# Local images
····
# Local tall images
····
# Local hero images
····
# Local logo images
····
# Local icons
····
```
</details>

**Comment by effcol** [comment]
Did you manage to get it working from Steam in the end? I see that you closed an report to do with this issue over at https://github.com/ValveSoftware/SteamOS/issues/830#issuecomment-1227721659 so fingers crossed!

**Comment by missionfloyd** [comment]
Yeah, it was a problem on my end. It works as-is.

**Comment by effcol** [comment]
Awesome thank you!

I'm really sorry though, I can't figure out how to get what goes in the terminal to work, how exactly do you set this up? Is there a terminal within Steam Rom Manager you have to run it through?

**Comment by missionfloyd** [comment]
It's just a list of settings to copy and paste. The important bits are:

Executable: `/usr/bin/flatpak`
Command line arguments: `run --command=mednafen com.github.AmatCoder.mednaffe "${filePath}"`
User's glob: `**/${title}@(.ccd|.CCD|.cue|.CUE|.m3u|.M3U|.toc|.TOC)`

Edit the existing Saturn preset with these values.

**Comment by effcol** [comment]
Ahh amazing thank you, I figured it out making a new preset using your Sega Saturn - Mednaffe(Flatpak) guide, I had to click on 'Parsers' in the right menu, and it worked perfectly! :D

The only thing I needed to change was I had to add  `|.7z|.7Z|.zip|.ZIP|.iso|.ISO|.chd` to the command line arguments, which I got from the existing Yabause preset, as a game which came in 2 disks that I had in a zip wasn't working. 
So that made the command line argument: `**/${title}@(.ccd|.CCD|.cue|.CUE|.m3u|.M3U|.toc|.TOC|.7z|.7Z|.zip|.ZIP|.iso|.ISO|.chd)`

Incidentally, while looking I saw in the 'Community Presets' section when you're on Parsers section, and 2 of the presets in the dropdown do support Beetle Saturn, using "Sega Saturn - Retroarch - Beetle Saturn" or "Sega Saturn - Retroarch(Flatpack) - Beetle Saturn". 
So there is a way to use a form of Madafen out the box. Plus I see you've submitted these to be added to the thread to be added to the app, so I guess I can mark this closed soon :D

**Comment by missionfloyd** [comment]
Mednafen doesn't support 7z, ISO, or CHD.

**Comment by effcol** [comment]
Ahh ok, thanks for clarifying, I guess I only needed to add `|.zip|.ZIP|`

**Comment by cbartondock** [comment]
Please submit a community preset for Mednaffe if you want!
