### ISSUE TITLE
Titles added to Steam get uncategorized every Steam restarts

### ISSUE THREAD

**Issue by Trezzanator** [doZennn/steam-rom-manager#357]
Hello, I am trying to keep my Steam library nice and organized and on top of adding systems for categories I am also categorizing by franchise. However, anything I upload into SRM all gets uncategorized upon my next login to Steam. I have tried Steam://resetcollections which works ok, but then I get an error if I attempt to make a new collection>

Has anyone else had a similar experience and if so have you been able to resolve it? Thanks!

**Comment by Darkcloud1987** [comment]
Yeah I have the same. Games suddenly disappeared from their collections Steam://resetcollections sets them back in to the collections but gives me an error message that reseting failed and on restart the games are out of the collections again. 
I actually made a long post on the Steam Forums about the solutions I tried, none worked: https://steamcommunity.com/discussions/forum/1/3458220484821978747/

**Comment by Trezzanator** [comment]
Glad I'm not the only one. I've been searching everywhere and trying all different types of solutions and nothing has worked.

**Comment by mcinnocent** [comment]
You are not alone 😇😢

**Comment by cbartondock** [comment]
This is happening because you have too many non steam shortcuts in steam, it is not an SRM issue, it is a steam issue. The limit appears to be somewhere around 3000 before categorization breaks.
