### ISSUE TITLE
Steam launch options of already added games are removed after adding new games

### ISSUE THREAD

**Issue by rybandrei2014** [doZennn/steam-rom-manager#358]
Hi I use Steam Rom Manager to add third party windows games to my Steam Deck, so far it works fine. The only issue I have that my custom launch options (proton prefixes etc.) are erased everytime I rerun Steam Rom Manager to add new games. Is there a possibility to load these launch arguments from some preconfigured .json file? In older release 2.2.26 I found "Custom Arguments JSON file capability + documentation" were added, but later it was removed for some reason from documentation in executable-arguments.md file... Was this functionality migrated somehow? Unfortunately I couldn't find any info in docs... Please let me know how do I set custom command line argument from predefined variable dependent on title's name. Thanks in advance

**Comment by cbartondock** [comment]
You can use the exception manager to do this, that's why the json was removed.
