### ISSUE TITLE
Google Images as secondary Image Provider

### ISSUE THREAD

**Issue by DocMAX** [doZennn/steam-rom-manager#362]
Like in mp3 tagger programs like MusicBee. If artwork is missing then there should be a button to get lets say top 10 results and pick them directly without file uploading promtps. Would be great and i wonder i am the first with this simple idea?

**Comment by cbartondock** [comment]
Sorry I don't think I am going to add anything like this. It's too much work for too little benefit. SGDB will get better and better over time. I'm happy to merge a PR but additional image providers just aren't on my radar right now.
