### ISSUE TITLE
PS3: Remove title id from name

### ISSUE THREAD

**Issue by exp111** [doZennn/steam-rom-manager#363]
When I import a game with the folder format '<Name> <TitleId>', the parser also uses that same name for the steam shortcut. This just looks weird and should probably be trimmed.

I don't think many people have multiple versions of the same game (and other parsers also don't attach the EU/US tag), so it should probably default to trimming the title id

**Comment by missionfloyd** [comment]
Did you forget something inside those quotes? Is it something like `The Last of Us [BCES01585]`?

There's already an option to remove things inside {parentheses} and [brackets].

**Comment by exp111** [comment]
> Did you forget something inside those quotes? Is it something like `The Last of Us [BCES01585]`?
> 
> 
> 
> There's already an option to remove things inside {parentheses} and [brackets].

Adding the title in brackets like 'Demons Souls [BLES00932]' parses fine into "Demon's Souls". The problem is that rpcs3 wants "Demon's Souls BLES00932" as a folder name, otherwise it doesn't show in the game list (maybe there's a way to change this?).

**Comment by missionfloyd** [comment]
Can you name it _just_ the title ID? That way, Steam ROM Manager will get the title from [customVariables.json](https://github.com/SteamGridDB/steam-rom-manager/blob/master/files/customVariables.json)

**Comment by exp111** [comment]
> Can you name it _just_ the title ID? That way, Steam ROM Manager will get the title from [customVariables.json](https://github.com/SteamGridDB/steam-rom-manager/blob/master/files/customVariables.json)

RPCS3 won't recognize only the id, and that would also make organising a pain. The id is always in the format ABCD12345 so why not just do a .* ([a-zA-Z]{5}\d{5})

**Comment by missionfloyd** [comment]
I just tried it, and it didn't seem to care what the folder was named.

**Comment by exp111** [comment]
If you choose a folder which contains multiple games, it only shows those in the specific formats. If you choose the game folder directly it doesn't matter (afaik). 

But if you work on a device like the steam deck, going through file explorers suck (or any desktop mode stuff without a mouse+kb)

So the real issue isn't that the title id isn't removed, but rather that the parser can't parse the default rpcs3 naming

**Comment by exp111** [comment]
So uhh you're right. I thought emudeck added those games automatically but as far as i can see rpcs3 doesn't have any automatic game directories (and I think I forgot that I added the games?). Tl;dr: just put the title into brackets.
