### ISSUE TITLE
[Feature Request] Select which roms are added from folder and ignore the rest

### ISSUE THREAD

**Issue by traynor1987** [doZennn/steam-rom-manager#364]
Would it be possible to add the following feature? 

I was wondering if it would be possible for me to add like 100 roms to a folder. Link the folder in SRM and then only pick like 10 to add to steam, meaning the rest can be played in emulation station. Like a toggle, the same way you have it for the emulators itself.

Currently using emu deck, so I need to add my favorites. Run SRM, add the favorites to steam then copy the other roms to the folder after.

If I ever want to add another single game. I need to delete the roms, add the roms I want to put in steam, run srm and then add the other games back again.

So hopefully this could be added and thanks for the great work.

**Comment by ghackt** [comment]
There should be an auto ignore for titles that already have compiled all art needed for the title to prevent freezing and also a long wait for reprocess after adding a few new titles. I have 550 titles myself that I love and actually play so it’s not really portable as described for title collectors.

**Comment by makmillion** [comment]
Agreed, SRM should compare the new list to existing entries and not remove/adjust the existing entries unless requested to do so.

**Comment by PhilippeCadieux** [comment]
> Would it be possible to add the following feature?
> 
> I was wondering if it would be possible for me to add like 100 roms to a folder. Link the folder in SRM and then only pick like 10 to add to steam, meaning the rest can be played in emulation station. Like a toggle, the same way you have it for the emulators itself.
> 
> Currently using emu deck, so I need to add my favorites. Run SRM, add the favorites to steam then copy the other roms to the folder after.
> 
> If I ever want to add another single game. I need to delete the roms, add the roms I want to put in steam, run srm and then add the other games back again.
> 
> So hopefully this could be added and thanks for the great work.

+1 on this. I think this would be the ideal solution usability wise. 

Another option that could work but not as user friendly could be some kind of inverted exception list (favorite list? Something like that) where you can tell which games you want in Steam.

**Comment by kencinder** [comment]
This isn't the first time something like this has come up, probably won't be the last, but it IS out of scope for SRM...which is a tool to bulk add games to Steam.
Too much work would go into making it into a tool where you pick and choose games to add, as it's been discussed before this is a feature that will not be added. There are already overrides to exclude titles which isn't any different than if an option was added to exclude elsewhere in SRM, it's far easier to sort ones games as needed, say in a subdirectory so they an still be found by any given app.

**Comment by cbartondock** [comment]
Yeah I would just like to add that this truly is easy. Create a subfolder where the games live and put the ones you want in steam in that subfolder. Have emu station search the parent folder recursively and tell srm to look only at the subfolder.
