### ISSUE TITLE
Query artwork by appID?

### ISSUE THREAD

**Issue by Marx1st** [doZennn/steam-rom-manager#365]
Hi!
In order for Steam to allow access to a games controller presets for non-steam games, the game's name has to be set to the appID of the same game in the steam store.
E.g. If I add "The Circle: Frontier" as a non-steam game, I can't access the communitie's controller presets. If I rename it to "868270" (the app's id), it works.
So, right now, I can create shortcuts with the games' names and SRM finds the cover art, etc. just fine, but I can't access the controller presets or I name the shortcuts with the app ids, controller presets work, but no artwork...

From what I understand SteamGridDB's api does support searching by app id. So, is this possible with SRM or are there any plans to implement this?

**Comment by cbartondock** [comment]
I don't plan to implement this to be honest, but you can currently use exceptions to do it (change the search title to the game's actual name or even include its sgdb id). Eventually I will add a search feature to the "fix match" page in preview which will make this process even easier.
