### ISSUE TITLE
Remove fuzzy list requirement and only use names from local source (file names/custom lists?)

### ISSUE THREAD

**Issue by doZennn** [doZennn/steam-rom-manager#366]
Some future changes to SGDB will break this functionality and right now it's causing more problems than it tries to solve.  
Best we start figuring out a better way to do naming.

**Comment by cbartondock** [comment]
set title modifier to `${title}` rather than `${fuzzyTitle}` and boom you're done. I gave up on fuzzyTitle a while back personally and where possible just started naming my files correctly
