### ISSUE TITLE
Translation into other locale

### ISSUE THREAD

**Issue by acer** [doZennn/steam-rom-manager#367]
I love the project and would like to help translate - is there some platform we can setup quickly to start getting translation for different locale?

**Comment by kencinder** [comment]
@cbartondock I think translations for anything are something worth doing where possible. Thoughts?

**Comment by cbartondock** [comment]
Everything that needs to be translated is in https://github.com/SteamGridDB/steam-rom-manager/tree/master/src/lang/english

If someone is willing to do this for their preferred language and submit a PR that adds the equivalent directory (e.g. `/src/lang/french`) then I will make the changes necessary to allow changing the language from settings.

**Comment by doZennn** [comment]
You may also contribute translations here if you don't want to do it via PR: https://crowdin.com/project/steam-rom-manager

I suggest using WYSIWYG mode when editing the .md files.
Please post here if the language you want to translate into is not listed and i'll add it.

**Comment by cbartondock** [comment]
I'm going to close this so people just use the crowdin platform.
