### ISSUE TITLE
Menu Based Overrides (Feature Request)

### ISSUE THREAD

**Issue by Lorgenz** [doZennn/steam-rom-manager#369]
Please add an option to right click a title in the generated preview and select "edit metadata" and let us enter into a search the game title and select the correct entry for a given game, ideally this should also show the file name and have options to override all fields that were automatically parsed. This would be a far more direct way to correct entries by using a  window or wizard instead of struggling to find the correct details in exceptions and going back and forth.

Summary: Menu based option for correcting entries with search functions to override incorrect entries generated in the preview.

**Comment by SentaiBrad** [comment]
Being able to remove entries that got added when a single game entry has multiple files (not multiple discs), for example, would be awesome too. Basically, a right-click context menu for several options.

**Comment by twharris57** [comment]
This would also be nice for adding direct links to the steam app db game you want to use, or to add an option to explicitly tell the parser that the search result it’s using was incorrect and it should try again. Actually, for fuzzy logic matches, giving a list of other potential matches so the user can pick an alternative would also be super nice to have.

**Comment by cbartondock** [comment]
Added essentially this in 2.4.5, it's not a search but it gives you the top ten SGDB matches to choose from. I might add a search in future but I am closing this for now.
