### ISSUE TITLE
553 Titles Issues

### ISSUE THREAD

**Issue by ghackt** [doZennn/steam-rom-manager#372]
I have 553 Titles and when I go to generate app list 2500 remaining providers starts decreasing for an example then it gets stuck randomly different times different numbers. 

There should be an option that only updates new titles added not current ones. So when I add a game it doesn’t go through the whole process all over again and get stuck. I have to keep generating until the remaining number reaches zero to be able to save app list combined with EMUDeck there is plenty of emulator support but easily able to reach 500+ favorite games so this issue should be something that should be fixed for large title collectors like myself.

**Comment by cbartondock** [comment]
Duplicate
