### ISSUE TITLE
Steam Link stops when SRM starts

### ISSUE THREAD

**Issue by pashdown** [doZennn/steam-rom-manager#374]
Steam Link connection fails when SRM starts.  Although I understand Steam cannot be running when SRM is, is it possible to retain Steam Link?  It is much easier to manage the desktop over Steam Link for the Steam Deck.

**Comment by missionfloyd** [comment]
You can use X11 forwarding for this. It doesn't work with flatpak though, so you have to use the appimage version of SRM.
