### ISSUE TITLE
Steam Deck - Steam parser not correctly identifying games

### ISSUE THREAD

**Issue by ghost** [doZennn/steam-rom-manager#376]
I installed the AppImage of Steam Rom Manager through EmuDeck on the Steam Deck. 

I am now trying to add a Steam Parser, using one of Steam Rom Manager's included layouts. 

I have the following configured: https://i3.lensdump.com/i/1TEyca.png, but when I generate my app list: https://i.lensdump.com/i/1TEGge.png, event log: https://i1.lensdump.com/i/1TEa3k.png, it only displays one game that's not actually in my Steam Library. 

I have CrossCode installed through the Linux itch.io client on my Steam Deck. I have no idea why it's appearing in the app list. None of my Steam games actually appear in the app list. 

It looks like my Steam parser isn't correctly picking up my library, but I'm not sure why.

**Comment by cbartondock** [comment]
Steam parser relies on your steam games having a category set.
