### ISSUE TITLE
Starting the Steam Rom Manager closes steam client on Steam Deck

### ISSUE THREAD

**Issue by deathxxx123** [doZennn/steam-rom-manager#381]
It's very embrasing...  Without steam i cannot use Virtual keyboard and cannot fix any options in manager.
What i need to to?
I try reinstall, but it tells me that will remove my saves and so.
Do i need use appImage version?

**Comment by missionfloyd** [comment]
It can't update the shortcuts while Steam is running.

I've been using the appimage version over SSH with X11 forwarding, rather than on the steam deck itself.

**Comment by doZennn** [comment]
This is unrelated to SRM. EmuDeck is doing this for whatever reason: https://github.com/dragoonDorise/EmuDeck/commit/bd20e7bcdf5533a6bf23a88f5beef09e01ee1121
