### ISSUE TITLE
Fatal error occurred in preview. see event view for details. Please try again later.

### ISSUE THREAD

**Issue by milenkosmagic** [doZennn/steam-rom-manager#382]
When attempting to generate app list, i'm getting the following error "fatal error occurred in preview. see event view for details. please try again later". 

Error encountered while saving user configurations!
Error: Cannot save without specifying parser type
All available image urls retrieved.
Executing parsers.
34 user configuration(s) was/were skipped (disabled by user).
3DO
Amiga - Retroarch
Amiga 600 - Retroarch
Amiga 1200 - Retroarch
Amiga CD - Retroarch
Arcade - MAME (standalone)
Arcade - RetroArch MAME 2003 Plus
Arcade - RetroArch MAME 2010
Arcade - RetroArch MAME Current
Arcade FBNeo - Retroarch
Atari 2600 - Retroarch - Stella
Atari Lynx - Retroarch - Beetle Handy
Bandai WonderSwan/Color - Retroarch - Beetle Cygne
Commodore 64 - Retroarch
DOS - Retroarch(Flatpak) - DOSBox Pure
Microsoft XBox - Xemu
Microsoft Xbox 360 - Xenia
Nintendo GameBoy - Retroarch - Gambatte
Nintendo GameBoy Color - Retroarch - Gambatte
Nintendo DS - Retroarch - melonDS
Sega CD/Mega CD - Retroarch - Genesis Plus GX
Sega Game Gear - Retroarch - Genesis Plus GX
SNK Neo Geo Pocket/Color - Retroarch - Beetle NeoPop
Sony PlayStation - DuckStation
Sony PlayStation - Retroarch - Beetle PSX HW
Sony PlayStation 2 - PCSX2
Sony PlayStation 2 - PCSX2 (old version)
Sony PlayStation 3 - RPCS3 (Extracted ISO/PSN)
Sony PlayStation Portable - Retroarch - PPSSPP
Sony PlayStation Portable - PPSSPP
Sony PlayStation 3 - RPCS3(Flatpak) (Installed PKG)
Arcade - Naomi
Nintendo Switch Ryujinx
NEC PC Engine/TurboGrafx 16 - Retroarch(Flatpak) - Beetle PCE FAST
1 user configuration(s) was/were skipped (invalid).
No title!
Please shutdown Steam if it is running.
Fatal error occurred in Preview. See event log for details.
Could not read required steam files:
 SyntaxError: /home/deck/.steam/steam/userdata/28176488/config/addedItemsV2.json: Unexpected end of JSON input
All available image urls retrieved.
Executing parsers.
34 user configuration(s) was/were skipped (disabled by user).
3DO
Amiga - Retroarch
Amiga 600 - Retroarch
Amiga 1200 - Retroarch
Amiga CD - Retroarch
Arcade - MAME (standalone)
Arcade - RetroArch MAME 2003 Plus
Arcade - RetroArch MAME 2010
Arcade - RetroArch MAME Current
Arcade FBNeo - Retroarch
Atari 2600 - Retroarch - Stella
Atari Lynx - Retroarch - Beetle Handy
Bandai WonderSwan/Color - Retroarch - Beetle Cygne
Commodore 64 - Retroarch
DOS - Retroarch(Flatpak) - DOSBox Pure
Microsoft XBox - Xemu
Microsoft Xbox 360 - Xenia
Nintendo GameBoy - Retroarch - Gambatte
Nintendo GameBoy Color - Retroarch - Gambatte
Nintendo DS - Retroarch - melonDS
Sega CD/Mega CD - Retroarch - Genesis Plus GX
Sega Game Gear - Retroarch - Genesis Plus GX
SNK Neo Geo Pocket/Color - Retroarch - Beetle NeoPop
Sony PlayStation - DuckStation
Sony PlayStation - Retroarch - Beetle PSX HW
Sony PlayStation 2 - PCSX2
Sony PlayStation 2 - PCSX2 (old version)
Sony PlayStation 3 - RPCS3 (Extracted ISO/PSN)
Sony PlayStation Portable - Retroarch - PPSSPP
Sony PlayStation Portable - PPSSPP
Sony PlayStation 3 - RPCS3(Flatpak) (Installed PKG)
Arcade - Naomi
Nintendo Switch Ryujinx
NEC PC Engine/TurboGrafx 16 - Retroarch(Flatpak) - Beetle PCE FAST
1 user configuration(s) was/were skipped (invalid).
No title!
Please shutdown Steam if it is running.
Fatal error occurred in Preview. See event log for details.
Could not read required steam files:
 SyntaxError: /home/deck/.steam/steam/userdata/28176488/config/addedItemsV2.json: Unexpected end of JSON input
All available image urls retrieved.
Executing parsers.
34 user configuration(s) was/were skipped (disabled by user).
3DO
Amiga - Retroarch
Amiga 600 - Retroarch
Amiga 1200 - Retroarch
Amiga CD - Retroarch
Arcade - MAME (standalone)
Arcade - RetroArch MAME 2003 Plus
Arcade - RetroArch MAME 2010
Arcade - RetroArch MAME Current
Arcade FBNeo - Retroarch
Atari 2600 - Retroarch - Stella
Atari Lynx - Retroarch - Beetle Handy
Bandai WonderSwan/Color - Retroarch - Beetle Cygne
Commodore 64 - Retroarch
DOS - Retroarch(Flatpak) - DOSBox Pure
Microsoft XBox - Xemu
Microsoft Xbox 360 - Xenia
Nintendo GameBoy - Retroarch - Gambatte
Nintendo GameBoy Color - Retroarch - Gambatte
Nintendo DS - Retroarch - melonDS
Sega CD/Mega CD - Retroarch - Genesis Plus GX
Sega Game Gear - Retroarch - Genesis Plus GX
SNK Neo Geo Pocket/Color - Retroarch - Beetle NeoPop
Sony PlayStation - DuckStation
Sony PlayStation - Retroarch - Beetle PSX HW
Sony PlayStation 2 - PCSX2
Sony PlayStation 2 - PCSX2 (old version)
Sony PlayStation 3 - RPCS3 (Extracted ISO/PSN)
Sony PlayStation Portable - Retroarch - PPSSPP
Sony PlayStation Portable - PPSSPP
Sony PlayStation 3 - RPCS3(Flatpak) (Installed PKG)
Arcade - Naomi
Nintendo Switch Ryujinx
NEC PC Engine/TurboGrafx 16 - Retroarch(Flatpak) - Beetle PCE FAST
1 user configuration(s) was/were skipped (invalid).
No title!
Please shutdown Steam if it is running.
Fatal error occurred in Preview. See event log for details.
Could not read required steam files:
 SyntaxError: /home/deck/.steam/steam/userdata/28176488/config/addedItemsV2.json: Unexpected end of JSON input
All available image urls retrieved.
Executing parsers.
34 user configuration(s) was/were skipped (disabled by user).
3DO
Amiga - Retroarch
Amiga 600 - Retroarch
Amiga 1200 - Retroarch
Amiga CD - Retroarch
Arcade - MAME (standalone)
Arcade - RetroArch MAME 2003 Plus
Arcade - RetroArch MAME 2010
Arcade - RetroArch MAME Current
Arcade FBNeo - Retroarch
Atari 2600 - Retroarch - Stella
Atari Lynx - Retroarch - Beetle Handy
Bandai WonderSwan/Color - Retroarch - Beetle Cygne
Commodore 64 - Retroarch
DOS - Retroarch(Flatpak) - DOSBox Pure
Microsoft XBox - Xemu
Microsoft Xbox 360 - Xenia
Nintendo GameBoy - Retroarch - Gambatte
Nintendo GameBoy Color - Retroarch - Gambatte
Nintendo DS - Retroarch - melonDS
Sega CD/Mega CD - Retroarch - Genesis Plus GX
Sega Game Gear - Retroarch - Genesis Plus GX
SNK Neo Geo Pocket/Color - Retroarch - Beetle NeoPop
Sony PlayStation - DuckStation
Sony PlayStation - Retroarch - Beetle PSX HW
Sony PlayStation 2 - PCSX2
Sony PlayStation 2 - PCSX2 (old version)
Sony PlayStation 3 - RPCS3 (Extracted ISO/PSN)
Sony PlayStation Portable - Retroarch - PPSSPP
Sony PlayStation Portable - PPSSPP
Sony PlayStation 3 - RPCS3(Flatpak) (Installed PKG)
Arcade - Naomi
Nintendo Switch Ryujinx
NEC PC Engine/TurboGrafx 16 - Retroarch(Flatpak) - Beetle PCE FAST
1 user configuration(s) was/were skipped (invalid).
No title!
Please shutdown Steam if it is running.
Fatal error occurred in Preview. See event log for details.
Could not read required steam files:
 SyntaxError: /home/deck/.steam/steam/userdata/28176488/config/addedItemsV2.json: Unexpected end of JSON input
All available image urls retrieved.
Executing parsers.
34 user configuration(s) was/were skipped (disabled by user).
3DO
Amiga - Retroarch
Amiga 600 - Retroarch
Amiga 1200 - Retroarch
Amiga CD - Retroarch
Arcade - MAME (standalone)
Arcade - RetroArch MAME 2003 Plus
Arcade - RetroArch MAME 2010
Arcade - RetroArch MAME Current
Arcade FBNeo - Retroarch
Atari 2600 - Retroarch - Stella
Atari Lynx - Retroarch - Beetle Handy
Bandai WonderSwan/Color - Retroarch - Beetle Cygne
Commodore 64 - Retroarch
DOS - Retroarch(Flatpak) - DOSBox Pure
Microsoft XBox - Xemu
Microsoft Xbox 360 - Xenia
Nintendo GameBoy - Retroarch - Gambatte
Nintendo GameBoy Color - Retroarch - Gambatte
Nintendo DS - Retroarch - melonDS
Sega CD/Mega CD - Retroarch - Genesis Plus GX
Sega Game Gear - Retroarch - Genesis Plus GX
SNK Neo Geo Pocket/Color - Retroarch - Beetle NeoPop
Sony PlayStation - DuckStation
Sony PlayStation - Retroarch - Beetle PSX HW
Sony PlayStation 2 - PCSX2
Sony PlayStation 2 - PCSX2 (old version)
Sony PlayStation 3 - RPCS3 (Extracted ISO/PSN)
Sony PlayStation Portable - Retroarch - PPSSPP
Sony PlayStation Portable - PPSSPP
Sony PlayStation 3 - RPCS3(Flatpak) (Installed PKG)
Arcade - Naomi
Nintendo Switch Ryujinx
NEC PC Engine/TurboGrafx 16 - Retroarch(Flatpak) - Beetle PCE FAST
1 user configuration(s) was/were skipped (invalid).
No title!
Please shutdown Steam if it is running.
Fatal error occurred in Preview. See event log for details.
Could not read required steam files:
 SyntaxError: /home/deck/.steam/steam/userdata/28176488/config/addedItemsV2.json: Unexpected end of JSON input

**Comment by lionelr96** [comment]
I had this exact issue for a bit. My solution was to make my way to the directory that contains addedItemsV2.json and delete it with the "rm" command and then it worked fine.

**Comment by cbartondock** [comment]
See `SyntaxError: /home/deck/.steam/steam/userdata/28176488/config/addedItemsV2.json: Unexpected end of JSON input`, 

@lionelr96's solution is correct. Somehow that file (which SRM uses to keep track of what it has added) got corrupted.
