### ISSUE TITLE
Title Override

### ISSUE THREAD

**Issue by OdinVex** [doZennn/steam-rom-manager#384]
Is there an easy way to tell SRM to just use the filenames (excluding extension)? SRM keeps detecting `Persona` as `Persona 5`. (To make SRM not detect chds in combination to the m3us they reside in, I chose to just create an m3u for each and every ROM, nicely named, too).

**Comment by OdinVex** [comment]
It's also failing on Guilty Gear X2, thinking it is Guilty Gear X2 #Reload. I'm wondering if this is a database issue, lack of an entry, or something.

**Comment by TheRadziu** [comment]
Same with "God of War HD" installed with pkg. Steam rom manager parses it as "God Of War Ghost of Sparta", and since i have this pkg also installed, seeing two and determining which is which on game list is annoying

Edit: God Of War II HD, God Of War Chains of olympus and God Of War Ghost of Sparta are parsed correctly.

**Comment by Sendaford** [comment]
**+1**

A general option to override the recognized game / manually specifiying the steamgriddb game-id  would be great, since localized titles often don't match either.

**Comment by OdinVex** [comment]
> **+1**
> 
> A general option to override the recognized game / manually specifiying the steamgriddb game-id would be great, since localized titles often don't match either.

Similar to how Kodi or Jellyfin can use things such as `tvdbid=XXX`, I like that. :)

**Comment by kencinder** [comment]
There are override options, including one to tell SRM to fetch a title and artwork from SGDB based on ID for any game you want a title overridden to, regardless of what it's filename is.
