### ISSUE TITLE
Workaround for Steam not tracking hours of RetroArch Steam Version entries?

### ISSUE THREAD

**Issue by natopotato390** [doZennn/steam-rom-manager#390]
When using RetroArch installed through Steam, Steam refuses to track individual game entry playtime hours/stats, It instead adds to the total hours for RetroArch on Steam.

![image](https://user-images.githubusercontent.com/87149753/191172891-cc1cb3b4-a5cb-46ae-b042-88ed28ef10ae.png)

Assuming this is an issue with Steam itself and not steamrommanager.

Does anyone know of any workarounds aside from just installing RetroArch seperately?

**Comment by soopercool101** [comment]
Steam doesn't track play hours or stats for any non-steam games, regardless of if they launch an actual steam game or not. Installing RetroArch separately would not fix this nor would anything else you can reasonably do.

**Comment by natopotato390** [comment]
You're right, not sure where the idea got in my head that steam tracked those hours.
Boy do I look dumb.
