### ISSUE TITLE
Preset feature

### ISSUE THREAD

**Issue by manuelx98** [doZennn/steam-rom-manager#391]
It would be really useful to have a "preset" feature for the active emulators on SRM. For people like me who have a big number of microsds divided per console on Steam Deck and have to remember which checks have to be switched on and which ones off (eg. "microsd 1": *disables all checks but Gamecube, Wii, N64*).
I thought of this because sometimes I forget to turn off some checks and get some collections on Steam cancelled.

**Comment by cbartondock** [comment]
Not sure I understand what is being asked here. You want presets for which parsers are enabled? I think that's a very niche feature, as most people have fewer than 15 parsers.

**Comment by manuelx98** [comment]
> Not sure I understand what is being asked here. You want presets for which parsers are enabled?

Pretty much, yes. Reason for that is that whenever you swap microSD and re-parse, if you mistakenly forget to un-check a parser using the wrong microSD, the entire collection gets deleted from Steam, and with it any customization made. I think it would come in handy for people with many microSDs and many parsers for each of them.

**Comment by cbartondock** [comment]
Why not just use the global roms directory environnement variable in settings? Then you only have to change one thing when you switch sds

**Comment by cbartondock** [comment]
Seems like a cleaner solution.

**Comment by manuelx98** [comment]
Sorry for the late reply.

> Why not just use the global roms directory environnement variable in settings? Then you only have to change one thing when you switch sds

It does not solve the problem unfortunately. Re-parsing with every parser checked, if you use a global ROMs directory for certain consoles only, it does not find the roms for the other ones and thus it removes their collections on Steam. You should still un-check the parsers not used every time you switch sds, to avoid srm deleting some steam collections.

**Comment by cbartondock** [comment]
Okay, I just think this is a very niche/meta feature. It's the kind of thing somebody can implement if they want, but I definitely won't.
