### ISSUE TITLE
Steam RetroArch now needs to be loaded through Sniper on Linux

### ISSUE THREAD

**Issue by soopercool101** [doZennn/steam-rom-manager#394]
As of the latest version of RetroArch on Steam, simply calling retroarch.sh no longer works. Instead, you need to call `"SteamLinuxRuntime_sniper/run" -- "retroarch.sh"` (paths simplified to be generic). There should be an option to set the sniper run path so that Steam copies of RA continue to work.

**Comment by Naitrate** [comment]
I'd definitely like to see some sort of way of using the Steam version of RetroArch on Steam ROM Manager. Reason being the cloud save support.

Got an idea on what I'd need to use for the executable configuration to set this up?

**Comment by cbartondock** [comment]
Can this not be accomplished just by changing the RetroArch executable string in global settings? Or do you want the presets changed? If so we would really have to make separate presets for steam retroarch

**Comment by soopercool101** [comment]
It cannot be set as the executable string last I checked as it requires multiple quotation marks, which breaks the current setup. Allowing this to work would be acceptable, though having a new preset would likely be optimal for users less willing to do in-depth setup like this

**Comment by cbartondock** [comment]
I suspect you could get it to work with backslashes in the correct places, but I can't test it in the near future. If you do, feel free to comment your parser as a preset in the ongoing issue about parser presets.

**Comment by cbartondock** [comment]
I am going to close this for lack of activity, I know for a fact people have the steam version of retroarch working through SRM.
