### ISSUE TITLE
Parser Option - "Remove (...) and [...] brackets" is detecting two disc games as the same game

### ISSUE THREAD

**Issue by ghost** [doZennn/steam-rom-manager#396]
SRM Version: 2.3.40
Steam Deck (SteamOS)

Turning this option on in a PCSX2 parser prevents both discs of "Xenosaga Episode III" from appearing properly. 

Photo of ROM names: https://i.lensdump.com/i/1Nln4K.png

Test Parser (Remove Brackets toggled on) - https://pastebin.com/raw/V1SjMiXX
Test Parser (Remove Brackets toggled off) - https://pastebin.com/raw/bBrvguE2

Parser Configuration: https://pastebin.com/raw/zTFJAmk4

**Comment by kencinder** [comment]
This is not an issue, SRM does not differentiate discs itself and only parses files, that option only removes brackets from a title.

The best solution is to do something like store multi disc games in a subfolder with an M3U outside with your single disc games.
Another option is to use glob-regex if you know what you are doing, to have SRM not detect subsequent discs and only change discs from the emulator itself when needed.

**Comment by ghost** [comment]
SRM should be showing all of the discs in a generated app list, regardless, if they're the correct file type. 

SRM is saying that both discs are somehow the same file, which is strange. It might be related to the fact that the disc names are in parentheses, "(Disc 1)", "(Disc 2)". 

It also happens for Metal Gear Solid, ROM names (ignore the m3u file): https://i1.lensdump.com/i/1bToFo.png

PCSX2 doesn't support M3U files at this time either.

**Comment by kencinder** [comment]
According to that log it doesn't appear to be doing anything incorrectly, the remove brackets option does exactly what it should for that title.

What happens(or should) in that case is you wind up with 2+ entries in Steam with the exact same title, SRM isn't adding the same file.
Neither SRM or Steamgriddb handle or provide different artwork or titles based on a specific disc, that is up to you to either not use that removal option or use exceptions to override titles or use local artwork for specific discs.

From what I can tell, the option is working exactly how it should.
Latest builds of pcsx2 do support m3u btw, has for a long time...just not the latest release version which is well outdated.

**Comment by Godsbane** [comment]
https://github.com/PCSX2/pcsx2/issues/6696 does not support m3u.

retroarch core may, no idea on that. (but would not use it)
