### ISSUE TITLE
Error when generating app list

### ISSUE THREAD

**Issue by Memeb0** [doZennn/steam-rom-manager#402]
![20221018_201741](https://user-images.githubusercontent.com/116128433/196568516-94c7d23e-a134-4272-bdb6-6654fd1befa2.jpg)

**Comment by TarasTech** [comment]
Im getting this issue aswell, It seems that the steam config might have changed, and the parser should now be looking into the /home/deck/.steam/steam/userdata/238199530/config/localconfig.vdf directory. The localconfig file seems to have the data that the steam parser is looking for

**Comment by jrobio** [comment]
I'm experiencing the same issue. I tried resolving the issue by deleting the userdata directory as well as removing all collections and then adding all steam games to a different collection. These changes were not reflected in sharedconfig.vdf and steam rom manager can't pick them up.

**Comment by cbartondock** [comment]
Issue is almost certainly that your steam games are not categorized, that's how SRM picks them up.
