### ISSUE TITLE
`Save app list` runs successfully but produces collections with zero entries

### ISSUE THREAD

**Issue by ADeane6** [doZennn/steam-rom-manager#405]
I'm running SRM on steam deck via emudeck

SRM Version: 2.3.40

The collections are created but with zero entries, there are no error logs in SRM and as far as I can tell everything ran fine, I've got roms in several different emulator categories and the collections for all are created but all have zero entires

Any ideas what could cause this or how best can I debug further is there anyway to read what the config is being set for the empty collections?

**Comment by McBruno712** [comment]
I have the same problem.

**Comment by cbartondock** [comment]
Any change in 2.3.46?

**Comment by McBruno712** [comment]
**Update:** after some research and troubleshooting I found out that, in my case, what was causing the bug was the MetaDeck plugin, uninstalling it and restarting my Deck solved the problem.

**Comment by cbartondock** [comment]
Okay, I suspect the other person had the same issue, so not an SRM thing.

**Comment by Rykst3r** [comment]
I'm starting to have this problem, and I don't have the MetaDeck plugin installed. It began doing this out of nowhere.
