### ISSUE TITLE
Games installed in Cemu are not detected

### ISSUE THREAD

**Issue by Abbin44** [doZennn/steam-rom-manager#406]
So first off I should tell you that I am using a Steam Deck, and the folder SRM is pointing to on the Wii u is ```/home/Emulation/roms/wiiu/roms``` where ```wiiu``` is the root folder of Cemu
If you decide to install the game in Cemu instead of simply loading it, the files end up in ```/home/Emulation/roms/wiiu/mlc01/usr/title/``` unless you manually change the folder.

This is of course not a bug, but it would be handy to have two file paths that would point to the rom folder and mlc folder respectively unless you wish to change them.  What I had to do to bypass this was to point the mlc path to the roms folder instead so that SRM would see all games no matter if they are installed or loaded.

Now, when the game (Which was Mario 3D World, ```ID: 00050000-10145D00```) showed up it appeared as the SNES game "Jungle Strike" even though it was recognized as a Wii U game, which sounds like a bug.

**Comment by cbartondock** [comment]
You can always just symlink both directories to a single directory and have srm parse that one recursively. As for your fuzzy matching issue, it's probably a bug in SGDB's search or just an unlucky result. Check with people on the discord if you have fuzzy matching issues
