### ISSUE TITLE
Issues with Dolphin not launching due to malformed command [Windows]

### ISSUE THREAD

**Issue by ghost** [doZennn/steam-rom-manager#409]
Doesn't matter which game I launch due to the formatting breaking (screenshot included of the command it spit out attempting to be run in powershell)

![image](https://user-images.githubusercontent.com/13430434/199387290-d564f199-05b3-492d-b6fa-b1daea6794b0.png)

**Comment by cbartondock** [comment]
This has nothing to do with steam rom manager.
