### ISSUE TITLE
Error occured while loading configuration presets

### ISSUE THREAD

**Issue by icecold0310-github** [doZennn/steam-rom-manager#412]
When run the Steam ROM Manager on Steam Deck, will see "Error occured while loading configuration presets", and there's no list for selecting!!!!

But when I tested Windows version, there's no problem!!!

Tried download from Github or install by using Flathub, same problem!!!

**Comment by AceAttorney** [comment]
same

**Comment by cbartondock** [comment]
Force download config presets. In future seek help on the discord for this problem.
