### ISSUE TITLE
Steam Deck Ryujinx flatpak doesn't launch games

### ISSUE THREAD

**Issue by Bboy486** [doZennn/steam-rom-manager#414]
The flatpak arguments doesn't launch the game within steam.

I used the template for ryujinx flatpak, saved and updated. When I went to launch the game (the game launches direct in ryujinx/desktop) nothing happens.

**Comment by icecold0310-github** [comment]
same thing happened here. When lunch a game, it's showing "RYU-004" error...

**Comment by cbartondock** [comment]
@kencinder any idea what this could be? I don't use flatpak emulators.

**Comment by kencinder** [comment]
No clue, but this post the OP edited to say they reinstalled and it solved the issue. I don't use them either.

https://www.reddit.com/r/EmuDeck/comments/10h326g/ryujinx_ryu004/

**Comment by cbartondock** [comment]
Okay closing.
