### ISSUE TITLE
Error when generating app list

### ISSUE THREAD

**Issue by morgandotexe** [doZennn/steam-rom-manager#415]
Whenever I try to generate an app list I get the error "X user configuration(s) was/were skipped (invalid)." Things were working perfectly fine before, I have noticed this as of updating emudeck today.

SRM version is 2.3.40 running on Steam Deck Linux 5.13.

**Comment by kencinder** [comment]
There have been new releases of SRM since this post, if there is still an issue please ask for assistance on Discord or open a new ticket
