### ISSUE TITLE
[SteamDeck] No in-software interface to duplicate images from one account to another

### ISSUE THREAD

**Issue by FindTheDoorToJesus** [doZennn/steam-rom-manager#416]
Currently on the SteamDeck, if you have more than one steam account on the gaming mode when you setup the images for the software; You will be met with images set for one account but not the other. So this makes adding roms into multiple accounts with the same rom covers, banners, grid, and heroes images a pain for those who want a professional look to the overall experience of the library grid list.

**Possible solution**
_Add a new setting which allows copying the directory of images from "Steam\userdata\<id3>\config\grid\" to the other users with different id3 so they may all have the same image in the game library._

**Current user solution until otherwise fixed**
Just copy the correct images you want shared with everyone else from the "Steam\userdata\<id3>\config\grid\" directory and overwrite the others id3 config folders.

**Comment by cbartondock** [comment]
This is now possible via import / export of artwork choices.
