### ISSUE TITLE
(Enhancement) More ways to change game image assets for app list entries.

### ISSUE THREAD

**Issue by samiscool51** [doZennn/steam-rom-manager#417]
I've found it annoying with how that it's not that easy to change the game hero from within steam or SRM
while SGDBoop can solve this issue for images uploaded to SGD, if the images are taken down or the user has custom images they can't share, they are plain outta luck.

so i decided to _try_ (not that well, im not a UI designer so please excuse my bad mock ups) and solve this with this proposal
i propose we replace the 'Add local images' on the app entry with a button 'Select app assets' button which goes to a gui to allow users to further customize their game image assets:

<details><summary>Example Mutiple image selector:</summary>
<p>

![Example mutiple image selector](https://user-images.githubusercontent.com/13957636/202833242-3bca8283-d246-44ea-b8f3-2eafe75930ac.png)

</p>
</details>

using the example [store graphical assets](https://partner.steamgames.com/doc/store/assets/standard) and [the SGD entry for dota 2](https://www.steamgriddb.com/game/15831), i've designed a gui where users can select what image each asset will use with the `select image` button going to another page where the user can select the image they wish to use and what image provider they want to use (if in the event SRM adds more in the future)

<details><summary>Example image selector:</summary>
<p>

![Example image selector](https://user-images.githubusercontent.com/13957636/202833750-45921476-8baf-4b8f-81da-57c123962948.png)

</p>
</details>

in my opinion i believe this system would make it easier for people to customize their assets more if they wish to.
also heres a quick write up of how each button will work:

- `Accept` button: in the mutiple image selctor it will accept the images the user has selected and apply them to the app assets. in the image selector, it will change the asset to the one the user has selected.
- `Cancel` button: will cancel the users actions in both windows while also removing any changes that the user may have done between the current window and the last window (e.g if the user has selected an image in the image selector window but presses cancel, the selection will not be applied)
- `Reset` button: in the multiple image selector, resets all the app assets to what SRM would normally apply. in the image selector, resets the selected app asset and only that selected app asset, to what SRM would normally apply
- `Browse` button: allows a user to select an image from their computer if they have designed their own assets (only available in the Image selector window)
- `Select image` button: goes to the image selector window and allows users to select what image that asset will have.

i hope you like it, regardless if it's not that great looking it doesn't have to look like that, so long as the feature is added i don't mind.

**Comment by cbartondock** [comment]
I'm not sure what this gui adds that the current UI doesn't have. If you change the artwork type to "All Artwork" this is basically what you get, except for the reset button and select provider (but currently there is only one provider anyway).

The ability to add local images is already there, it's a little icon in the corner of the app preview in SRM.
