### ISSUE TITLE
Collection overwrite not supported?

### ISSUE THREAD

**Issue by natopotato390** [doZennn/steam-rom-manager#418]
I'm attempting to create a collection on steam called "TV GAMES". 
This will include *both* regular steam games and the non-steam ones made by SRM.

When I try to use ${TV GAMES} in SRM with a "TV GAMES" collection already made and containing a few steam games,
It either makes a duplicate collection with just the SRM games, or does nothing at all. 
Does not add the app entries to the existing collection.

It also seems if I drag regular steam games into the collection made by SRM, then run SRM again it removes the steam games.
Is this just not supported?

**Comment by cbartondock** [comment]
This has been added in master, will be in the next release.
