### ISSUE TITLE
Zelda BOTW can't be parsed.

### ISSUE THREAD

**Issue by sneakyjoeru** [doZennn/steam-rom-manager#419]
Trying on steamdeck. Cemu sees zelda and DLC installed, as well as paths are setup so it shows the game in the list of games, however when I try to preview-generate app list, it asks me to shut down steam. Happens only if I have WiiU roms parsing enabled, if I have emulators turned on - it generates emulators list just fine in the same situation. Wrong error. Same error in the logs.
The issue is caused by an incorrect parser rom path in parser settings. Fixing rom path fixes the issue.

**Comment by cbartondock** [comment]
The asking you to shutdown steam happens every time, regardless. It's not an error, it's advice. Otherwise saving category information won't work (artwork will still save).
