### ISSUE TITLE
Uplay parser extract wrong game titles

### ISSUE THREAD

**Issue by SpaceFrags** [doZennn/steam-rom-manager#421]
Uplay parser do not extract correct names of the game, for examples Assassin's Creed Unity being l1 and Beyond Good and Evil being GAMENAME.

![Screenshot 2022-11-24 162252](https://user-images.githubusercontent.com/13735192/203819129-13d873b6-1111-428b-82a3-969a692c2985.png)

**Comment by kudos** [comment]
I'm having the same problem. Possible commonality, for me it's also the second game of 2 that has the problem, and that game is also on a secondary drive.

**Comment by cbartondock** [comment]
All my Uplay games are on a secondary drive so that's not it. If both of you could dm me on discord, I am lontanadascienza, I would like you to send me some files to debug the issue.

**Comment by cbartondock** [comment]
This will be fixed in 2.3.51
