### ISSUE TITLE
amazon games parser recognizes uninstalled games as installed

### ISSUE THREAD

**Issue by wec22** [doZennn/steam-rom-manager#425]
if a game has been installed previously, but has been uninstalled, the parser still sees the game and thinks it is installed.  There is a column in the sqlite db for installed that the parser does not check.  The parser gets the valid list based on whether or not it exists in the db at all.  a game that has been uninstalled will still exist in the db, but have the installed field set to 0. 

I would open a pr to fix it, but my background is not in typescript so I am lost on how to make the change.

**Comment by cbartondock** [comment]
Thanks for all of the info, I will fix this soon.

**Comment by cbartondock** [comment]
Fixed in 2.3.48
