### ISSUE TITLE
SRM no longer working as intended

### ISSUE THREAD

**Issue by MicheleGiunto** [doZennn/steam-rom-manager#426]
Up until yesterday it worked fine (both with +5000 games AND along with Boilr for PC games). Yesterday it started behaving like crazy.
1. It no longer remembered the custom artwork I inserted for some games. Heck, it doesn’t remember it downloaded artwork in the first place. So everytime it downloads them from scratch, wasting time and battery life
2. When I try re-uploading custom artwork or try to do everything else, it hangs. With no chance of restoring its activity. And then I start EVERYTHING all over again
3. Trying to play by its new deranged rules is no good either. I try to save the app list, and it freezes, and often just crashes. Giving me the collections assigned to Steam but with no artwork at all.
The log is perfectly normal (when it allows me to access it without freezing), with no abnormalities whatsoever.

**Comment by kencinder** [comment]
There have been new releases of SRM since this post, if there is still an issue please as for assistance on Discord or open a new ticket
