### ISSUE TITLE
Steam as executable for RetroArch version of Steam currently not possible

### ISSUE THREAD

**Issue by DFelten** [doZennn/steam-rom-manager#428]
Currently I'm trying to add games for the Steam version of Retro Arch for my Steam Deck. Unfortunately I don't know how to set the Steam Rom Manager so that I can specify steam as executable. 

The games must be started like this:

`steam -applaunch 1118310 -L  "/run/media/mmcblk0p1/steamapps/common/RetroArch/cores/mednafen_psx_hw_libretro.so" "/run/media/mmcblk0p1/Emulation/roms/psx/Wild Arms (USA).m3u/Wild Arms (USA).m3u"`

With this start directory:

`/run/media/mmcblk0p1/steamapps/common/RetroArch/`

![image](https://user-images.githubusercontent.com/1169185/210177408-d3b11800-e636-4ec1-a7f8-577f44b92292.png)

When creating the Steam entry manually it's working like described in the image on the Steam Deck. This is a valid entry to run a Steam game and then select the RetroArch core with the game.  

But within the Steam Rom Manager `steam` is invalid as executable, and it seems that there and I am not allowed to specify a path there. Leaving it empty does not work either. Is that even possible at the moment? If so, what must be specified for this?

The current configuration

```json
{
    "parserType": "Glob",
    "configTitle": "Steam: Sony PlayStation - Retroarch - Beetle PSX HW",
    "steamCategory": "${PlayStation}",
    "steamDirectory": "${steamdirglobal}",
    "romDirectory": "${romsdirglobal}/psx",
    "executableArgs": "steam -applaunch 1118310 -L  \"/run/media/mmcblk0p1/steamapps/common/RetroArch/cores/mednafen_psx_hw_libretro.so\" \"${filePath}\"",
    "executableModifier": "\"${exePath}\"",
    "startInDirectory": "/run/media/mmcblk0p1/steamapps/common/RetroArch/",
    "titleModifier": "${fuzzyTitle}",
    "imageProviders": [
        "SteamGridDB"
    ],
    "onlineImageQueries": "${${fuzzyTitle}}",
    "imagePool": "${fuzzyTitle}",
    "defaultImage": "",
    "defaultTallImage": "",
    "defaultHeroImage": "",
    "defaultLogoImage": "",
    "defaultIcon": "/home/deck/.config/EmuDeck/backend/configs/steam-rom-manager/userData/img/default/icon.png",
    "localImages": "",
    "localTallImages": "",
    "localHeroImages": "",
    "localLogoImages": "",
    "localIcons": "",
    "userAccounts": {
        "specifiedAccounts": "",
        "skipWithMissingDataDir": true,
        "useCredentials": true
    },
    "executable": {
        "path": "",
        "shortcutPassthrough": false,
        "appendArgsToExecutable": true
    },
    "parserInputs": {
        "glob": "*/${title}@(.m3u|.M3U)"
    },
    "titleFromVariable": {
        "limitToGroups": "",
        "caseInsensitiveVariables": false,
        "skipFileIfVariableWasNotFound": false,
        "tryToMatchTitle": false
    },
    "fuzzyMatch": {
        "replaceDiacritics": true,
        "removeCharacters": true,
        "removeBrackets": true
    },
    "imageProviderAPIs": {
        "SteamGridDB": {
            "nsfw": false,
            "humor": false,
            "styles": [],
            "stylesHero": [],
            "stylesLogo": [],
            "stylesIcon": [],
            "imageMotionTypes": [
                "static"
            ]
        }
    },
    "parserId": "167258616173134308",
    "version": 10
}
```

**Comment by natopotato390** [comment]
I think the only way to do this is to point to the RetroArch .exe directly. This is how it's done with all the RetroArch presets.

![image](https://user-images.githubusercontent.com/87149753/211126027-79fc65c3-e457-41d1-9b43-a33dc08d9431.png)

You are basically trying to create a NON-steam shortcut for an ACTUAL steam game which I don't think is possible.

**Comment by DFelten** [comment]
When creating the Steam entry manually it's working like described above on the Steam Deck:

`steam -applaunch 1118310 -L "/run/media/mmcblk0p1/steamapps/common/RetroArch/cores/mednafen_psx_hw_libretro.so" "/run/media/mmcblk0p1/Emulation/roms/psx/Wild Arms (USA).m3u/Wild Arms (USA).m3u"`

This is a valid entry and on the Steam Deck with Linux it's working to run a Steam game like this. 

The problem is the Steam Rom Manager. It seems that the Steam Rom Manager is not able to create such entry.

**Comment by natopotato390** [comment]
Apologies, I misread and now I understand,
I tried it out and sure enough it worked (though I had to put the args under "Launch Options" instead)
I'm on windows and I was able to get it to work 2 ways
1. by putting in the full filepath to steam.exe and "-applaunch 1118310" at the beginning of Command line arguments
(pointing to the exe filepath directly functions exactly the same as "steam -applaunch ..." though I don't know for linux)
![image](https://user-images.githubusercontent.com/87149753/211178880-784cdc01-a34a-4af9-a683-11719f643a40.png)

2. just leaving "Executable" blank and putting "steam -applaunch 1118310" in "Executable modifier"
![image](https://user-images.githubusercontent.com/87149753/211178938-cdc29f66-08b9-4ef7-acb5-045294f242ee.png)

Both function the same
![image](https://user-images.githubusercontent.com/87149753/211179208-867ac269-b0fd-4a2b-80cd-7ac6ed83a3dd.png)
![image](https://user-images.githubusercontent.com/87149753/211179026-c58c26b6-6350-45da-b3cc-e6877a2afcf3.png)

For me, just pointing to the RetroArch exe functions exactly the same as the above options, Steam say's I'm playing RetroArch and tracks hours under that title.
Sounds like this way won't work on linux for whatever reason though.
Hope this helps.

**Comment by DFelten** [comment]
Thanks for your answer. I thought this is not possible with Linux, but now it's working when selecting the `steam.sh` as executable. It's working for the Steam Deck with this configuration:

Executable: `/home/deck/.steam/steam/steam.sh`

Command line arguments: `-applaunch 1118310 -L "/run/media/mmcblk0p1/steamapps/common/RetroArch/cores/mednafen_psx_hw_libretro.so" "${filePath}"`

**Comment by DFelten** [comment]
Unfortunately there is a problem when starting the game via steam.sh. The Steam Deck can no longer close the game properly. The console hangs. If the game is started directly via `steam -applaunch`, this does not happen. I suspect that `steam.sh` creates a new steam instance, whereas the `steam` command uses the existing one. 

So, unfortunately, the solution does not work after all. 

The easiest solution would be to allow the Steam Rom Manager to do this. Currently, however, it is indicated that the configuration is not valid.

**Comment by cbartondock** [comment]
If you type "which steam" into terminal what comes up?

**Comment by cbartondock** [comment]
The issue here is that SRM currently does not support using OS path variables in any of it's fields, see [issue 375](https://github.com/SteamGridDB/steam-rom-manager/issues/375). If you replace "steam" with the output of `which steam` things will work fine, SRM just requires a valid path in the executable field. I'd leave this up to remind me to eventually implement path parsing, but [issue 375](https://github.com/SteamGridDB/steam-rom-manager/issues/375) has that covered.
