### ISSUE TITLE
Feature Request: Custom Platform Parsers (for flatpak)

### ISSUE THREAD

**Issue by Blackerererer** [doZennn/steam-rom-manager#435]
Hello,
I would like to add a custom platform parser for ScummVM. The reason is that ScummVM can provide a fuller name, which is then easier to match with any online databases. Looking at the ts files, I can probably write the typescript myself, but updating flatpak and the binary is kind of annoying, if you want to keep smooth updates. So the request is for external typescript scripts for custom platform parsers.

**Comment by Blackerererer** [comment]
I gave up and wrote my own platform parser for ScummVM. Just ironing out some nice-to-have features.

**Comment by cbartondock** [comment]
Feel free to submit a PR

**Comment by Blackerererer** [comment]
I am still wrestling a bit with flatpaked SRM on Linux. Im new to this - node.js, flatpaking, electron - and it seems nontrivial to get access to scummvm.ini across flatpaks. Ive tried direct "--list-targets" on ScummVM binary, but ScummVM is not so well written to not call SDL_init(), even if a parameter makes run in CLI mode (happens way before than setupGraphics()), both on Windows and Linux, so running ScummVM through flatpak-spawn complains about X11 display not being present. I have 2 options now, try getting an X11 to the flatpak-spawned ScummVM or parse scummvm.ini, with the latter seeming a bit nicer. Getting scummvvm.ini may either require flatpak-spawn cat (which may or may not work, and does not seem right), or using flatpak-portal, maybe through DBus. The later is a bit arcane to me at this point, but I think I can figure it out.
