### ISSUE TITLE
Missing/incorrect entries for RPCS3 (flatpack (installed pkg)) parser

### ISSUE THREAD

**Issue by Kellidus** [doZennn/steam-rom-manager#436]
Jak 3 HD (serial number NPUA80708) and Metal Gear Solid Peace Walker HD (serial number NPUB30611) can't be parsed. Jak II HD (serial number NPUA80707) parses incorrectly as Jurassic Park III: The DNA Factor.

**Comment by recon117** [comment]
Having the same problem with Resistance 3 (serial number BCES01118) , it pulls the game up, but duplicates it and marks the copy as Spy Kids 3-D. Seems to be an ongoing issue for some people.

**Comment by Kellidus** [comment]
> Having the same problem with Resistance 3 (serial number BCES01118) , it pulls the game up, but duplicates it and marks the copy as Spy Kids 3-D. Seems to be an ongoing issue for some people.

I thought it would be sadly. Hope it gets fixed

**Comment by kencinder** [comment]
Pull requests are welcome to https://github.com/SteamGridDB/steam-rom-manager/blob/master/files/customVariables.json to fix missing or incorrect entries

**Comment by nabilfreeman** [comment]
I noticed Peace Walker was fixed in #577 .

I've opened a new PR: #603 that sorts out the Jak games.

**Comment by cbartondock** [comment]
PRs were merged.
