### ISSUE TITLE
which release do i install....................... im on PC

### ISSUE THREAD

**Issue by St1nGxD** [doZennn/steam-rom-manager#438]
idk if this looks like a joke but i actually don't know which release i should install.

**Comment by St1nGxD** [comment]
idk if this looks like a joke but i actually don't know which release i should install.

**Comment by kencinder** [comment]
Windows - The Setup or Portable executables, a matter of preference

Linux - .deb is like an installer for Debian based distributions, otherwise the AppImage is portable and usable on any distro
