### ISSUE TITLE
Epic parser not appending launchOptions correctly

### ISSUE THREAD

**Issue by Meistache** [doZennn/steam-rom-manager#442]
I lack skills on JS to actually fix it (not sure if I'm losing any syntax), but I've noticed that, although the parser code do try to push launch options when parsing, the launch options aren't properly configured on the parsed Steam launcher, thus not including the proper URL in this field. This means that, in order to effectively launch the game on steam link / remote play / big picture we need to go the manual way, otherwise the window won't go foreground and sometimes the game doesn't open at all. This would be a very appreciated fix as doing this manually is really boring (I just dug the code because I was after some tips on how to do this as a custom parser but then it already exists).

**Comment by cbartondock** [comment]
I am not sure I understand the issue, could you give an example with screenshots of what is happening?

**Comment by cbartondock** [comment]
Closing due to lack of response
