### ISSUE TITLE
Steam Parser Failed - Steam changed internal database structure or parser tried to read an outdated database.

### ISSUE THREAD

**Issue by stluc** [doZennn/steam-rom-manager#443]
Hi, I get this error with the Steam parser, I already applied to all games, software, tools, videos and software some category (also a big general one for all of them), but it does not seem to be the reason, any idea?
I also set properly the path and username as far as I can tell. Thanks for any help

> Testing "Steam" parser (SRM version - 2.3.40 Non-Portable).
> Operating system is "Windows 11"
> Testing failed
> Error: File Parser Execution:
>  > Steam parser failed with fatal error:
>  > Steam changed internal database structure or parser tried to read an outdated database.
> Problematic file: undefined
> Full error:
>  undefined

![image](https://user-images.githubusercontent.com/38380407/220874437-908f4251-a30b-4e2c-85a3-13093614c84c.png)

**Comment by cbartondock** [comment]
Just fixed this in in master.

**Comment by cbartondock** [comment]
Fixed 2.3.41
