### ISSUE TITLE
SRM not updating the version flag when updating.

### ISSUE THREAD

**Issue by Xarishark** [doZennn/steam-rom-manager#473]
winget reads the first installed version even after an update. SRM should update its version flag so winget does not requests an update for it for no reason. 
![image](https://user-images.githubusercontent.com/21146743/228618416-15c95f25-6495-41b4-bfb8-1c3c78fe1536.png)

**Comment by cbartondock** [comment]
Not exactly sure where I would do this, in the registry?

**Comment by Xarishark** [comment]
The location of the key is in the same place the install/uninstall info is assigned.

Screenshots show that the installed version and the version on the reg are not the same. During the installation/update process a registry key update of the version needs to be implemented.

![Screenshot 2023-05-05 005447](https://user-images.githubusercontent.com/21146743/236338499-5cd61dbe-19cc-4305-9d9f-b65c5f2951dc.png)


![image](https://user-images.githubusercontent.com/21146743/236338883-cec2ee4a-540a-4674-bf4a-dbf6a8d7962b.png)

**Comment by cbartondock** [comment]
This appears to have been fixed when I brought all the dependencies up to date with 2.4.0. Presumably this was an oversight in older versions of electron's auto updater. Let me know if this is still an issue and I will re-open.
