### ISSUE TITLE
 Midnight Fight Express on UWP Json parse error

### ISSUE THREAD

**Issue by tlt21** [doZennn/steam-rom-manager#500]
When Midnight Fight Express on gamepass is installed UWP fails to parse. After removing the game it succeeds. It will fail again after reinstall.

Testing "UWP" parser (SRM version - 2.3.52 Non-Portable).
Operating system is "Windows 11"
Testing failed
Error: File Parser Execution:
 > UWP parser failed with fatal error:
 SyntaxError: Unexpected token t in JSON at position 4327

**Comment by tlt21** [comment]
There is specialized characters that are not being escaped by the converTo-json method in powershell, causing a broken json object. 
![image](https://user-images.githubusercontent.com/25313909/231651844-15748415-1761-4ca3-88ce-4147fa6f3664.png)

**Comment by cbartondock** [comment]
Merged the PR
