### ISSUE TITLE
Publish to microsoft store in msix format

### ISSUE THREAD

**Issue by soredake** [doZennn/steam-rom-manager#509]
Example benefits of msix package format:
 https://github.com/felixrieseberg/windows95/issues/221 https://learn.microsoft.com/en-us/windows/msix/overview#key-features

**Comment by cbartondock** [comment]
Doesn't seem like electron-builder offers to package as misx, sorry. I will keep an eye on their updates to see if they add it.

**Comment by soredake** [comment]
@cbartondock .msi/.exe can be repacked into .msix:
https://learn.microsoft.com/en-us/windows/msix/packaging-tool/tool-overview
https://learn.microsoft.com/en-us/windows/msix/packaging-tool/package-conversion-command-line
https://learn.microsoft.com/en-us/windows/msix/packaging-tool/create-app-package

**Comment by cbartondock** [comment]
That would need to go into our github workflow somehow. If you can find an example of a github workflow that does it I'll consider adding.
