### ISSUE TITLE
Hang at executing parsers

### ISSUE THREAD

**Issue by MicheleGiunto** [doZennn/steam-rom-manager#513]
After the in-app update now I’m unable to add more than 1000 games, or else SRM hangs at “Executing parsers” and after a while it goes completely black.
I don’t know what is the problem. Tried doing each parser separately but as an example the NES alone has more than 1000 games, crashing SRM anyway.

**Comment by cbartondock** [comment]
Hmmm. Did you check the logs? Any errors? It shouldn't hang, there should be errors.

**Comment by cbartondock** [comment]
Do you mind messaging me on the discord @lontanadascienza so we can work out exactly what is going on with your system? I have no issues of this kind.

**Comment by Yumyumsauce1** [comment]
I’ve been having issues since the update too.  It used to take about 10 minutes to find the images/urls to my roms.  Now it hangs indefinitely and never finishes.

**Comment by caffineehacker** [comment]
Also broken for me. Looks like there may be a memory leak or other issue with merging VDF entries. When adding the games to Steam, the rom manager process uses all of the ram and starts swapping until the OS kills it or completely hangs up.

**Comment by cbartondock** [comment]
Okay hanging at executing parsers and hanging at merge vdfs are totally unrelated issues. Please create a new issue and refrain from commenting here about anything after "executing parsers"

**Comment by cbartondock** [comment]
@MicheleGiunto any dice in the newest versions?

**Comment by MicheleGiunto** [comment]
> Hmmm. Did you check the logs? Any errors? It shouldn't hang, there should be errors. 

I can't even access the logs since it completely freezes

**Comment by MicheleGiunto** [comment]
> @MicheleGiunto any dice in the newest versions?

Is there a new version? I'll test it out. If it doesn't work, then I'll try DMing you on Discord.

EDIT: still doesn't work. It seems not to like so many roms. I've DMed you on Discord

**Comment by cbartondock** [comment]
I just did 1500 games no problem, so I think this is a setup specific or game specific issue

**Comment by cbartondock** [comment]
User solved their issue by updating emudeck.

**Comment by MicheleGiunto** [comment]
As previously stated by @cbartondock, the latest Emudeck update (Emudeck, not SRM), fixed everything. So the thread is closed

**Comment by krazykriskomar** [comment]
Why isn't this fixed on steam deck yet?
