### ISSUE TITLE
Names with dots (like F.E.A.R., hack.gu etc) not getting parsed!

### ISSUE THREAD

**Issue by v00d00m4n** [doZennn/steam-rom-manager#517]
Despite fixing bug with dots i suggest to do double search of any of such names - 1st attempt with dots, second without, like this F.E.A.R. > FEAR

**Comment by doZennn** [comment]
I think this might be a SGDB search algo issue. I'll check it out over the weekend. "F.E.A.R." should get you the correct game.

**Comment by cbartondock** [comment]
@v00d00m4n is the issue that they're not getting parsed at all or that the name is getting set incorrectly?

**Comment by cbartondock** [comment]
This would appear to be an SGDB issue, I search F.E.A.R. and I get zero results. Closing this as it's not an SRM issue, they'll fix it eventually.

**Comment by doZennn** [comment]
This is fixed now btw.

**Comment by cbartondock** [comment]
okay great
