### ISSUE TITLE
Missing scroll bar in preview

### ISSUE THREAD

**Issue by nille02** [doZennn/steam-rom-manager#518]
In the SRM 2.4.6 there is no longer a vertical scroll bar.

**Comment by cbartondock** [comment]
Lol whoops. Will fix right now.

**Comment by cbartondock** [comment]
Actually I can't reproduce this. You do know the scrollbar only appears if you have enough apps to need it?

**Comment by cbartondock** [comment]
Oh I see, the problem is on smaller screens. The scrollbar is not gone, it's just too far to the right for you to see it.

**Comment by cbartondock** [comment]
Basically we have too many buttons on the bottom bar

**Comment by nille02** [comment]
Do the buttons need the space in full? or reducing the with a bit. in that case we can also get rid of the vertical scroll bar. and yes, its a small screen 1280x800px steam deck.

**Comment by cbartondock** [comment]
Fixed in 2.4.7
