### ISSUE TITLE
steam rom manager error occurred while loading configuration presets

### ISSUE THREAD

**Issue by Cooky006** [doZennn/steam-rom-manager#520]
Since I updated to the new version I get the above error message and cannot prefill to create new parsers. Has this happened with anyone else? Tried a reinstall and still the same error

**Comment by Cooky006** [comment]
![Screenshot 2023-04-21 171445](https://user-images.githubusercontent.com/131476388/233685144-c6069f56-6452-40d5-b773-5f2be8e97388.png)

**Comment by Perseida0** [comment]
Got the same issue after updating, and I don't know how to solve it yet.

**Comment by cbartondock** [comment]
Force download config presets in settings.

**Comment by Cooky006** [comment]
Thanks so much :) Worked perfect
