### ISSUE TITLE
SRM does not start

### ISSUE THREAD

**Issue by gitrys** [doZennn/steam-rom-manager#521]
Version: all installed or portable versions since 2.4
Windows 11, newest Patches
Started as Administrator or with standard privileges.

When i try to start SRM (i tried all versions since 2.4, 2.3.x does work fine) it won't work. There is the loading symbol in the middle. I waited 15 minutes or so but the issue persists. 
![grafik](https://user-images.githubusercontent.com/54995488/233685186-a8188ab2-79b1-4c03-a614-d491ce041742.png)

**Comment by cbartondock** [comment]
Try hitting ctrl + R to reload, failing that hit `ctrl+shift+i` to bring up the debug menu. Go to the console and send me a screenshot, it should show some error.

**Comment by gitrys** [comment]
Hi there, thank you for your work!

The reload did nothing, the screenshot shows the console:
![grafik](https://user-images.githubusercontent.com/54995488/233775420-c63b8992-8de7-44f7-aad9-3d5f31b50810.png)

"Der Befehl "powershell" ist entweder falsch geschrieben oder konnte nicht gefunden werden."

-> This translates to, that "powershell" is either wrong written or could not be found. 

If i start my powershell normally, its not a problem, so i suggest its not a problem at my end?

Best regards

**Comment by cbartondock** [comment]
Oh wow interesting, that is almost certainly a localization issue of some kind. I guess based on the code that a dependency of srm (os-name) uses PowerShell but fails to account for the name/path being different on a non English machine. I will make an issue with them and in the mean time add a try catch block around the system info code.

**Comment by cbartondock** [comment]
Actually it seems like the issue is this one: https://github.com/ethereum/remix-desktop/issues/147

And you need to add powershell to your path: https://github.com/ethereum/remix-desktop/issues/147#issuecomment-1266984971

In the meantime though, SRM definitely shouldn't error out if it can't get the system information, so I will add a try-catch block there.

**Comment by cbartondock** [comment]
Oh here is another person who had an issue with a German machine, so potentially localization. I would bet your powershell executable is differently named: https://github.com/sindresorhus/windows-release/issues/27

**Comment by cbartondock** [comment]
Okay this is fixed in master, SRM handles the error now and you just get a slightly less pretty os name. Will be in 2.4.8.
