### ISSUE TITLE
preview UI issues

### ISSUE THREAD

**Issue by jenkshi** [doZennn/steam-rom-manager#526]
I have an with issue with Emudeck UI where the drop down menus at the top will be covered by the preview menu blow it.

here is an example:
here you can see the drop down menu is hiding behind the preview menu which make it unclickable.
  
![Screenshot_20230426_213425](https://user-images.githubusercontent.com/47603870/234657206-707b1f7e-64c9-4f93-95d4-bc57947aa35c.png)

![Screenshot_20230426_213505](https://user-images.githubusercontent.com/47603870/234657216-a7d52cc0-cecf-4d62-9dae-031e9109d0a7.png)

**Comment by cbartondock** [comment]
Yep dragoon and I are on it.

**Comment by jenkshi** [comment]
thanks guys. and I am very thankful for your great work

**Comment by cbartondock** [comment]
Fixed as of 2.4.10
