### ISSUE TITLE
Add a setting to use the previous UI

### ISSUE THREAD

**Issue by Martmists-GH** [doZennn/steam-rom-manager#533]
The current UI doesn't allow for customization of parsers, and being able to edit this when emudeck overwrites the configs is one of the best features the old UI had. Why was this removed?

**Comment by cbartondock** [comment]
There is such a setting. Under Settings > theme. Use Deck or Classic if you want to edit parsers. The EmuDeck theme is the "for dummies" theme that just uses pre-configured parsers from emudeck.
