### ISSUE TITLE
Multiple ROM Dirs?

### ISSUE THREAD

**Issue by DocMAX** [doZennn/steam-rom-manager#545]
Here is what i try to achieve. If this is not supported, can you add it?
![grafik](https://user-images.githubusercontent.com/5351323/236623429-1022ae9c-e1b5-48d9-b779-007d98859295.png)

**Comment by cbartondock** [comment]
This is achieveable using absolute paths and braced sets in the glob field of the parser. Set the `ROMS DIRECTORY` field to whatever valid path you want, e.g. `D:`, it will be ignored if you use absolute paths in the glob. Then set your `USER'S GLOB` field like this:

`{d:/roms/switch,n:/roms/switch/xci}/${title}.@(nsp|xci|NSP|XCI)`

Adding in whatever extensions you want.
