### ISSUE TITLE
Override Legendary command

### ISSUE THREAD

**Issue by DocMAX** [doZennn/steam-rom-manager#547]
Can you extend Legendary option in a way i can edit the startup command?

From; Complete shortcut - "d:\games\windows\platforms\Epic\GTAV\PlayGTAV.exe"
To: Complete shortcut - "c:\myscripts\legendary.vbs 9d2d0eb64d5c44529cece33fe2a46482"

**Comment by cbartondock** [comment]
I'm not sure exactly what you're asking for here, you want to be able to set the startup command to something completely different? That's not really how SRM is designed to work, it doesn't allow you to override shortcuts on an individual level, it pulls in shortcuts from other places (in this case legendary).
