### ISSUE TITLE
Default Steam Images as an image source

### ISSUE THREAD

**Issue by rombat** [doZennn/steam-rom-manager#548]
When using Steam parser, is there a way to keep/load Steam default artworks?
For some titles and artwork types, I'd like to keep the default ones, but I can't find out how.

**Comment by cbartondock** [comment]
Currently there is no way to do this as all of our images come from SGDB. There is no website that hosts official steam artwork and has an api, so I would have to scrape their cdn directly. I could do it, so this will eventually get added. I was hoping that by now someone would have added an actual api, but alas.

**Comment by rombat** [comment]
And could it be possible to allow the exclusion of an artwork type replacement for a given game?
Even if the default artwork is not displayed.

**Comment by rombat** [comment]
SGDB can display original Steam assets, so maybe something can be done with this

**Comment by cbartondock** [comment]
I am going to close this issue as I don't plan to implement it unless steamgriddb adds some `official steam artwork` api.
