### ISSUE TITLE
Follow .Ink or .desktop option issues on Linux

### ISSUE THREAD

**Issue by NullScope** [doZennn/steam-rom-manager#549]
On the Steam Deck I've created a "Windows" parser for all my Windows game, this parser looks at a folder I created manually with `.desktop` files and adds the games to Steam.

I need to turn on the option `Follow .Ink or .desktop to destination` otherwise the game won't start.
Naturally I also need to add a Command line argument `STEAM_COMPAT_MOUNTS=/run/media/mmcblk0p1` as I need proton to mount my microSD card as the games are installed in there.

The games created by Steam Rom Manager in the Steam properties will have two issues:
- `Start In` will have an opening `"` but not a closing one (e.g `"/run/media/mmcblk0p1/games/SomeGame`).
- `Launch Options` will be empty.

The game will still somehow start with the incorrect `Start In` path but in some cases such as a `setup.exe` "game" it will not mount my microSD card.

By turning the option off, both the `Start In` and `Launch Options` get filled in correctly.

Steps to reproduce:
- Create a `.desktop` file pointing to a `.exe` file (doesn't have to be a valid `.exe`).
- Turn on `Follow .Ink or .desktop to destination`.
- Set the User's glob to `**/${title}.desktop`.
- Add the command `STEAM_COMPAT_MOUNTS=/run/media/mmcblk0p1` in the command line arguments.
- Run and save the parsed games.

**Note:** This might be a global issue, but I haven't tested on Windows yet, just the Steam Deck.

**Comment by NullScope** [comment]
I've just tested this in Windows, and its same the outcome, except `Start In` is correct

@cbartondock any luck reproducing this issue?

**Comment by cbartondock** [comment]
If you use `follow lnk to destination` the start in directory and the launch arguments from the `.lnk` or `.desktop` file will be used, the ones you set in SRM will be ignored. Is that what you're doing? You're setting them in the shortcut file and SRM is pulling them incorrectly?

**Comment by NullScope** [comment]
Hi @cbartondock, I believe that was not the case, however its been a long time since I have messed with Steam ROM Manager, I will try to reproduce the issue again

**Comment by cbartondock** [comment]
No problem, let me know.

**Comment by cbartondock** [comment]
I am unable to reproduce this. If `follow lnk to destination` is set, SRM pulls the start directories and launch arguments from the shortcuts correctly. If it isn't set, it takes them from the parser correctly. I will re-open if you still have a problem, but it seems like you just need to set the start directory and launch arguments in the shortcuts themselves, which is the intended (and documented) behavior for `follow lnk to destination`.
