### ISSUE TITLE
build:linuxdir electron-version

### ISSUE THREAD

**Issue by Blackerererer** [doZennn/steam-rom-manager#550]
Hi,
I would like to check, if anyone tried to run build:linuxdir recently. Trying to do so natively on ArchLinux and Im bumping into missing electron-version file in the root. Is that an issue on my end, or on yours, please? I was trying to merge on Apr 28 with 11d363ef being the most recent.

Cheers

**Comment by cbartondock** [comment]
I haven't tried it recently but I will check it out. This is used for building flatpaks, is that what you're trying to do? Otherwise it's `build:linux`

**Comment by Blackerererer** [comment]
> I haven't tried it recently but I will check it out. This is used for building flatpaks, is that what you're trying to do? Otherwise it's `build:linux`

That is correct. Ive managed to do build:linux fine. The thing is, that I did not run into this exact issue with the code from November or something like that. I almost have ScummVM parser ready. I just need to catch up with the master and verify that both Windows and Linux (with and without Flatpak for both SRM and ScummVM) work

**Comment by cbartondock** [comment]
We upgraded electron and all srm's other dependencies with 2.4.0, so it's possible it may be broken now. I am not near my Linux machine but I will test when I get back.

**Comment by Blackerererer** [comment]
I have noticed. Also looks more stylish :). Well done.

**Comment by cbartondock** [comment]
Aw thanks! The UI overhaul was @dragoonDorise he crushed it.

**Comment by Blackerererer** [comment]
Hi,
did you get a chance to take a look at it, please? I really want to get to testing of my code with the updates, so that I can wrap it up :D. My next effort will probably be somehow integrating DosBoxGameLauncher or some other DosBox profile manager (thats what they are essentially), because all dos games are a bit of a pain to manage compared to console ROMs and they hardly follow any predictable structure. Hence using some tool to prepare configurations and then just using it to launch or at least get a good

**Comment by cbartondock** [comment]
I was out of action for a while, back now! I will take a look.

**Comment by cbartondock** [comment]
Fixed, somehow the electron-version file got removed. I successfully built a flatpak so this is working again.
