### ISSUE TITLE
Automatically select alternate images for the DMCAd ones

### ISSUE THREAD

**Issue by felipecrs** [doZennn/steam-rom-manager#552]
It would be really great if the Steam Rom Manager could automatically look for alternate images instead of proposing to use a DMCAd art:

![image](https://github.com/SteamGridDB/steam-rom-manager/assets/29582865/4367ae55-40bb-4c5e-a354-d4e6b762f2b5)

And there are alternatives:

![image](https://github.com/SteamGridDB/steam-rom-manager/assets/29582865/b1037d60-730f-4b0c-bce1-0d208aca01b4)

**Comment by kencinder** [comment]
This is a Steamgriddb issue that they're being shown and returned, out of SRMs control.

**Comment by felipecrs** [comment]
@kencinder I wonder if SRM can't detect such situation and automatically skip such images. For example, download the image, check if it has the same checksum as the DMCA image, if it has, skip it, select next, and so on.

**Comment by kencinder** [comment]
@cbartondock Would have to answer that one, I think it's a good idea if possible though, nobody wants the DMCA image used.

**Comment by cbartondock** [comment]
Good idea, I will add it

**Comment by cbartondock** [comment]
@doZennn best way though would be if the sgdb api had an option to not return dmca'd images? Is this already part of the API?

**Comment by cbartondock** [comment]
Actually filtering out DMCA'd artwork on SRM's end is easy. I guess I am just wondering if anyone thinks there is any reason not to. Should I add a toggle to include DMCA'd art, in case people want to see which art has been taken down?

**Comment by cbartondock** [comment]
For now I'll just filter them out, I can re-open if people strongly want the toggle.

**Comment by felipecrs** [comment]
I agree.

**Comment by kencinder** [comment]
I don't see the point of an option, if people want to see what has been DMCA they can use the SGBD website.

**Comment by felipecrs** [comment]
Ref https://github.com/SteamGridDB/steam-rom-manager/commit/df4c4aee11a8cde1f4c0985d2a677f21a24a3cc7
