### ISSUE TITLE
Support for Steam Controller templates

### ISSUE THREAD

**Issue by josephruggiero** [doZennn/steam-rom-manager#555]
Right now, the controller manager goes through each saved template and looks for templates ending with `(SRM)` for each controller type defined [here](https://github.com/SteamGridDB/steam-rom-manager/blob/master/src/lib/controller-manager.ts)

This list doesn't have an element for Steam Controllers, though, which would be `controller_steamcontroller_gordon`

That prevents SC users (all 10 of us) from using this feature

**Comment by cbartondock** [comment]
Are they always named that way? That is `controller_steamcontroller_gordon`?

**Comment by cbartondock** [comment]
Added in master (all controller types in https://partner.steamgames.com/doc/features/steam_controller/action_manifest_file)
