### ISSUE TITLE
(Citra,dolphin and,ppsspp) Roms don't load properly in steam deck game mode

### ISSUE THREAD

**Issue by jenkshi** [doZennn/steam-rom-manager#556]
Hi recently when I launch any ROM from (Citra,dolphin and,ppsspp) in steam deck game mode, instead of loading the game directly it takes me to the emulator menu and force me to chose the game from the emulator game list.

**Comment by jenkshi** [comment]
.

**Comment by kencinder** [comment]
This is a usage issue and not a bug, please seek support via Discord.
