### ISSUE TITLE
EA Desktop parser fatal error - 'tagName' undefined

### ISSUE THREAD

**Issue by Lulech23** [doZennn/steam-rom-manager#560]
Full error message:

```
Testing "EA Desktop" parser (SRM version - 2.4.16 Portable).
Operating system is "Windows 11"
Testing failed
Error: File Parser Execution:
 > EA Desktop parser failed with fatal error:
 TypeError: Cannot read properties of undefined (reading 'tagName')
```

This occurs with default settings from selecting the EA Desktop community parser preset. Customizing settings makes no difference in my attempts, but there's not much I can change without being incorrect to my installation. Creating a new parser and selecting the "EA Desktop" parser type also produces the same results.

My EA Desktop version is 12.186.0-5443

**Comment by ThomasCr** [comment]
I have the same problem.... I use a different Game Directory on a other Drive.
```
Testing "EA Desktop" parser (SRM version - 2.4.17 Non-Portable).
Operating system is "Windows 10"
Test fehlgeschlagen
Error: File Parser Execution:
 > EA Desktop Parser mit folgendem Fehler fehlgeschlagen:
 TypeError: Cannot read properties of undefined (reading 'tagName')
```

**Comment by cbartondock** [comment]
This appears to be an issue with https://github.com/NaturalIntelligence/fast-xml-parser. I'll look into updating it and if that doesn't fix the issue I'll report it to them.

**Comment by cbartondock** [comment]
Issue was this one https://github.com/NaturalIntelligence/fast-xml-parser/issues/620

Fixed in master by updating fast-xml-parser.

Let me know if it's still broken in 2.4.26 and I will re-open.
