### ISSUE TITLE
Match ${title} based on first letter

### ISSUE THREAD

**Issue by eskay993** [doZennn/steam-rom-manager#561]
I am trying to modify the PS3 Installed PKG parser to only match folders that begin with a specific letter. My PKG games are installed in RPCS3's default `/dev_hdd0/game/` folder which is the folder I'm parsing.

Is there a way to modify the following `User's Glob` to match only titles/folders that start with the letter `N`? Or alternatively ignore folders that begin with `B`?

```
${title}/USRDIR/@(eboot.bin|EBOOT.BIN)
```

So `NPUB30609//USRDIR/EBOOT.BIN` should match and extract `${title}` as `NPUB30609`, and `BCES01585/USRDIR/EBOOT.BIN` should be ignored.

The reason for this is that `/dev_hdd0/game/` also contains additional folders installed by my disc based games such as DLCs, updates, etc. These all begin with the letter `B`. This is creating duplicate matches with my PS3 Extracted ISO parser, which looks in a different folder.

The link for `extended glob marchers` in the help section is not loading (just a blank screen), so not sure if the answer is there.

Is this possible? Or is there another way I can achieve this in a automated way? 

Many thanks.

**Comment by kencinder** [comment]
This should be possible now with the changes in the above PR, if `Skip file if variable was not found` is enabled in the parser
