### ISSUE TITLE
Performance issues with VERY large ROMs libraries

### ISSUE THREAD

**Issue by erkexzcx** [doZennn/steam-rom-manager#564]
Steam Deck, Flatpak application, version 2.4.16.

Currently this app cannot do this:

1. Cannot remove all entries from Steam when 6k+ ROMs are added. Also see https://github.com/SteamGridDB/steam-rom-manager/issues/563#issuecomment-1566004477
2. Cannot "Save to Steam" 20k+ ROMs. Application just hungs with blank screen on it.

In short, this application needs to have some serious performance improvements and proper progress bars.

**Comment by erkexzcx** [comment]
Looks like RAM is an issue here. Is there a way to reduce RAM usage during "Save to Steam" operation?

**Comment by krazykriskomar** [comment]
This is not fixed. Happens to me every time.

**Comment by cbartondock** [comment]
Have you guys tried disabling artwork providers and just adding the games without artwork? That would narrow down the issue somewhat. I suspect too much artwork is being processed in ram at once.

**Comment by cbartondock** [comment]
Fixed in master. Let me know if it isn't when the next version drops.
