### ISSUE TITLE
Category Error: Cannot read properties of undefined

### ISSUE THREAD

**Issue by Raiden8816** [doZennn/steam-rom-manager#567]
(reading 'WebStorage')

Tired to install BattleNET last night using NonSteamLaunchers. However it did not create a BattleNET shortcut and has ruined all my rom organization with SRM.

Any help would be appreciated.

**Comment by doZennn** [comment]
NonSteamLaunchers is a ticking time bomb and should not ever be used.  
I suggest submitting an issue to their repo telling them that they are breaking categories: https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/issues
