### ISSUE TITLE
Icon for rom is present in steam library, but missing in desktop shortcut

### ISSUE THREAD

**Issue by soredake** [doZennn/steam-rom-manager#568]
In steam:
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/5204968/e16a5db2-4c07-44cd-a370-0ddc92e7a962)

When i create desktop shortcut:
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/5204968/f0f68d24-f509-4cd8-8f19-0ffb0a82cd7c)

**Comment by Godsbane** [comment]
i don't think this is an SRM bug, but rather a steam bug.

![image](https://github.com/SteamGridDB/steam-rom-manager/assets/1683513/22a2c93f-58ee-4056-a138-fe8bb0c79ee6)

This is a normal steam game with the same issue.

**Comment by soredake** [comment]
It seems that windows supports only this formats for icons 
![изображение](https://github.com/SteamGridDB/steam-rom-manager/assets/5204968/f722bbe4-eedf-4b9e-bf38-2d0062d85936)

While steam supports this:
![изображение](https://github.com/SteamGridDB/steam-rom-manager/assets/5204968/44978b63-56bb-4449-8f14-0605797c0008)

It seems that this can't be solved on windows.

**Comment by soredake** [comment]
The only "fix" i can imagine is for steam-rom-manager to convert png to icon and create shortcuts for games.

**Comment by soredake** [comment]
https://aka.ms/AAo13go

**Comment by kencinder** [comment]
This is a Steam issue, not SRM. Steam creates the desktop shortcut, SRM has nothing to do with it.
