### ISSUE TITLE
Retain width when changing themes

### ISSUE THREAD

**Issue by ghost** [doZennn/steam-rom-manager#573]
When you change the width of the left sidebar, it resets when you change themes:

Default width: 

![image](https://github.com/SteamGridDB/steam-rom-manager/assets/108900299/d2dfdb72-212e-4618-b134-a8c83b1edac2)

Adjusted width (as an example):

![image](https://github.com/SteamGridDB/steam-rom-manager/assets/108900299/5f98b0f5-fd20-4f38-b856-c7308d240bb4)

Change the theme to `Deck` or `EmuDeck`, change it back to `Classic` and the width resets back to the default width. Seems to happen when changing from one theme to another.

It looks like part of the issue is in `userSettings.json`:

```
	"batchDownloadSize": 50,
	"language": "en-US",
	"theme": "Classic",
	"offlineMode": false,
	"navigationWidth": 743,
	"clearLogOnTest": false,
	"version": 6
}
```

The `navigationwidth` is tied to the theme and can't be changed on a "per-theme" basis. 

Would it be possible to retain the width for each theme instead and not have it reset when changing themes?  In addition, would it be possible to adjust the width on a per-theme basis in `userSettings.json`?

**Comment by cbartondock** [comment]
This is fairly reasonable behavior by SRM: setting values to the themes default upon switch. It's a niche case to be constantly switching between themes. Configurable styling is maybe coming in the future, but I am going to close this for now.
