### ISSUE TITLE
Feature Request: Auto-exclude files listed in m3u

### ISSUE THREAD

**Issue by monyarm** [doZennn/steam-rom-manager#575]
Maybe a toggleable option for parsers "Ignore files listed in m3u"?
Cause right now, I have to put my multidisc chd's in a separate folder, and have the m3u point to them.

**Comment by kencinder** [comment]
SRM isn't going to read inside M3U files. Having multi disc games in a different folder with the M3U pointing to them is one acceptable solution. There are many ways to accomplish this, including using Regex.
