### ISSUE TITLE
Request timed out after 10000 milliseconds on Deck

### ISSUE THREAD

**Issue by qfoxb** [doZennn/steam-rom-manager#583]
I've tried all the solutions listed under the previous issues of similar nature, and nothing is working. Every single title I have spits out request timed out. No covers are imported to steam. I've tried smaller batch sizes, preload images, hotspot, wired connection etc. nothing works. I'm on latest release via Emudeck

**Comment by rahmatrmdn** [comment]
same here

**Comment by nonobio** [comment]
Hi,

I have the same issue but on Windows.

**Comment by nonobio** [comment]
This is my log id if it can help: LHYX3U
Thanks

**Comment by xWILDWINGx** [comment]
Experiencing the same issue on WiFi and Ethernet. I suspect it has something to do with pi-hole running on my network, but haven't been able to confirm that yet.

**Comment by kencinder** [comment]
Betting on this being an issue with Steamgriddb at the time, closing

**Comment by antony-s-king** [comment]
I'm on Deck and had this issue. I switched altered my WiFi network configuration for IPv6 to "Disabled". This fixed it for me.
