### ISSUE TITLE
[Feature Request] Whitelist or Inverted Exceptions List

### ISSUE THREAD

**Issue by RotKingJoey** [doZennn/steam-rom-manager#584]
Currently I am utilizing the Exceptions list in the unintended way of marking off all games I'm not currently playing.
I know that this isn't recommended but with patience it gives me the intended result of only allowing a select few games I want in my library.

I was wondering if it would be possible to implement a whitelist that could only generate art and shortcuts to Steam for games in that list, and everything would be re-parsed as normal rather than relying on an bloated exceptions list.

Without going into too much detail, I have a large library of games to pull from but much like my currently installed Steam games I don't realistically want to see them all at the same time. I have a particular folder structure that I need to keep my game images in so relocating the ones I want to currently play to a different folder for SRM to parse wouldn't be the best solution in my case.

If there is no way you would like to develop this feature, I will continue to use the degraded performance option I currently am, but I figured it wouldn't hurt to ask.

**Comment by cbartondock** [comment]
Why not just put the games you want in a subfolder or give them special titles eg. `Game title (enabled)` and use the parser features to select them? As you say, this is the opposite of the intended use of the exception manager. What you're asking for is currently possible using just the matching tools of the parser.
