### ISSUE TITLE
Local images glob correctly resolves image when testing parser but includes images that match any game in preview screen

### ISSUE THREAD

**Issue by jwp327** [doZennn/steam-rom-manager#587]
I have set up a parser with the local portraits glob: `${localimagesdir}${/}box${/}@($fuzzyTitle}|${title}).@(png|jpg)`

When I go to test parser I see:

Portraits glob: `C:/Games/Roms/art/box/@(Banjo-Kazooie|Banjo Kazooie).@(png|jpg)`
Resolved portraits: `file:///C:/Games/Roms/art/box/Banjo%20Kazooie.png`

and so on for the rest of my games.

When I go to Preview and select Parse, however, each game has all the artwork for all games matched by that parser. So, for example, Banjo Kazooie will have the art from Banjo Kazooie, Banjo Tooie, Ocarina of Time, etc. And Banjo Tooie will have the art from BK, BT, OOT, etc, and so will OOT, with the result that for each game, you have to scroll through it all to get to the right game's image.

**Comment by cbartondock** [comment]
I am unable to reproduce this, and I use a lot of local artwork. For me, in preview, each game has only its own local artwork. Is this still a problem in the latest version of SRM (2.4.24)?

**Comment by cbartondock** [comment]
Closing for lack of response. Let me know if you still have the same issue on the latest versions and I will re-open.
