### ISSUE TITLE
Exporting images does not create a selections.json, but importing images errors out for no selections.json being present

### ISSUE THREAD

**Issue by trialhero** [doZennn/steam-rom-manager#588]
As the title suggests, when I export, it seems to just dump pictures into a directory. I assumed this was as intended. When I attempt to import them back, however, I get an error saying a _selections.json was not found. Is there a way to create this file otherwise? Is there an option I am missing. Thank you.

**Comment by cbartondock** [comment]
I am unable to reproduce this, for me _selections.json is always produced when exporting. Are you sure it's not hidden on your filesystem for some reason? It should be in the same directory as the images.
