### ISSUE TITLE
SRM unable to assign local images with semicolon in file name:

### ISSUE THREAD

**Issue by monyarm** [doZennn/steam-rom-manager#590]
```
Error: Non fatal errors occurred while writing:
Error for title Harry Potter: Hogwarts Mystery:
Error: ENOENT: no such file or directory, copyfile '////mnt/Games/_art/grid/Android/Harry Potter' -> '/home/monyarm/.steam/steam/userdata/72740846/config/grid/2269808932.jpg'
```

The file is called "Harry Potter: Hogwarts Mystery.jpg"

**Comment by kencinder** [comment]
Use a `-` in the filename, instead of a colon, extremely simple solution.
It's likely this would require special handling as it's an illegal character on Windows.

**Comment by monyarm** [comment]
I never said I was on windows.
And yes it would be a "simple solution", to just rename the games. But it's still not a proper solution.

**Comment by kencinder** [comment]
I never said you were, but adding platform specific checks for something so simple is not likely to happen. Using a colon in a filename is very non standard practice, and I have never seen one in any proper rom set.

**Comment by monyarm** [comment]
This is also an issue with the local portraits glob, as the finalTitle can contain a semicolon, but the filename of the image can't. Meaning it won't automatically find the images.
