### ISSUE TITLE
the analyze test function crashes

### ISSUE THREAD

**Issue by youtubeeicarlos** [doZennn/steam-rom-manager#591]
the analyze test function crashes in the current version, when trying to read 1471 DS roms for desmume

**Comment by youtubeeicarlos** [comment]
![Uploading 20230914_211420.jpg…]()

**Comment by youtubeeicarlos** [comment]
![20230914_211420](https://github.com/SteamGridDB/steam-rom-manager/assets/144261319/7e4aae58-f204-413f-a315-d6d3e05a3673)

Also looking at other packs, I noticed that it limited the number of roms it can read, for example I have 1353 gba roms, but it read 1141

**Comment by youtubeeicarlos** [comment]
I did a new test, if I use the analyzer without the folders for the images, it works!  BUT this causes images not to be generated and Steam Rom Manager to close.

**Comment by kencinder** [comment]
I do believe this was discussed on Discord, there is no issue with the number of files SRM reads and this issue is otherwise lacking.

If you have a problem with usage of SRM, please use the Discord, Github is for reproduceable bugs and features.

**Comment by youtubeeicarlos** [comment]
> Eu acredito que isso foi discutido no Discord, não há problema com o número de arquivos que o SRM lê e esse problema está faltando.
> 
> Se você tiver problemas com o uso do SRM, use o Discord, o Github é para bugs e recursos reproduzíveis.

They never answer me on the server, but I saw people on Discord with the same problem, without finding a solution🤡
