### ISSUE TITLE
[Steam Parser] Fails to detect synchronized collections

### ISSUE THREAD

**Issue by Martmists-GH** [doZennn/steam-rom-manager#596]
As editing collections on the steam deck itself is difficult, I prefer maintaining them on my PC instead. These are automatically synchronized to the Steam Deck.

However, SRM's parser does not see any games in the synchronized collection, even when the collection is modified locally.

**Comment by cbartondock** [comment]
This is fixed in master since the new steam parser doesn't rely on categorization.
