### ISSUE TITLE
Edge Cases for First Time Users / Fresh Steam Installs

### ISSUE THREAD

**Issue by CarJem** [doZennn/steam-rom-manager#597]
Just a couple of suggestions for some adjustments that I've noticed SRM can't handle:
- The Steam Parser Fails unless you pre populate the games in `sharedconfig.vdf` somehow... maybe this should at least be mentioned to avoid confusion
- if `..../steam/userdata/__USER__/config/grid/` does not exist, images will not be copied. Prehaps we should ethier point that out, or make the folder so they can be added, cuz this "grid" folder doesn't exist on a fresh install

**Comment by kencinder** [comment]
1: This is documented in SRM

![image](https://github.com/SteamGridDB/steam-rom-manager/assets/3614897/461972cd-6f6c-4409-9a8b-480689d1eceb)

2: #600
