### ISSUE TITLE
[Feature req.] Image overlays

### ISSUE THREAD

**Issue by zyrill** [doZennn/steam-rom-manager#601]
In the screen where "image choices" are managed for the roms with the possibility of choosing various pictures, instead of choosing one picture for portraits, banners etc. for each rom, the possibility of choosing two pictures, i.e. a background picture and an overlay picture for each orientation (portrait, banner) for the rom would be great. That would make it possible to add platform logos on top of various designs which would make configuring the appropriate picture that much easier. Currently, I sometimes click for minutes through dozenz of pictures until I find the one that has the appropriate platform branding.

**Comment by cbartondock** [comment]
This is just not how it works unfortunately - those images are sourced from https://steamgriddb.com, you'd have to get them to change how all of their artwork is stored (and re-do hundreds of thousands of pieces of artwork).
