### ISSUE TITLE
[Request] PS3 - Custom Variable should separate Disc & PSN games

### ISSUE THREAD

**Issue by Immersion95** [doZennn/steam-rom-manager#606]
This could be an easy fix to [that issue](https://github.com/SteamGridDB/steam-rom-manager/issues/561).

SRM creates shortcuts for games and their updates which is bothersome, separating it should solve it as Extracted ISOs should be in "rpcs3\games" and PSN games in "rpcs3\dev_hdd0\game"

Variable : 
PS3 : Disc based -->BLUS/BLES/BLAS/BCUS/etc..
PSN : NPEB/NPUB/etc..

I'll gladly do the PR.

**Comment by eskay993** [comment]
:+1: 

This would be awesome if it's of interest to the SRM team! :)  I'm sure others have encountered this as well.

**Comment by Immersion95** [comment]
I created the PR, hope it's accepted :)

**Comment by eskay993** [comment]
Ah that's what you meant about changing custom variables! Genius! :) I didn't think of that but that should work. Thanks for the PR. Hopefully it goes through.
