### ISSUE TITLE
Allow disabling built-in updater

### ISSUE THREAD

**Issue by soredake** [doZennn/steam-rom-manager#612]
I install and update SRM from winget, so i don't need this built-in updater:
![изображение](https://github.com/SteamGridDB/steam-rom-manager/assets/5204968/39acaa1e-6bb6-413d-9fad-105d3f81149e)

**Comment by cbartondock** [comment]
Good idea! I'll add it.

**Comment by cbartondock** [comment]
Added in master.

**Comment by soredake** [comment]
Thank you!
