### ISSUE TITLE
Help report the false positive on www.steamgriddb.com and steamgriddb.com in Quad9.net

### ISSUE THREAD

**Issue by pdsakurai** [doZennn/steam-rom-manager#613]
Hi,

I suddenly cannot connect to SteamGridDB's services and have just figured out today that Quad9.net blocks any DNS queries to the mentioned domains in the title.

Here are the screenshots:
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/23254804/9c00105f-2a62-4036-ae74-d5d7aba115be)
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/23254804/688a1bfc-3a00-4305-a949-1b7ec0c6abae)

Please help in reporting this false positive on [this link](https://quad9.net/result?url=www.steamgriddb.com).

Thank you!

**Comment by fpiesche** [comment]
This has been resolved - not really an SRM problem but SGDB's admin reported the problem with the affected providers who have fixed it.

**Comment by pdsakurai** [comment]
Confirmed no longer blocked as of writing.
