### ISSUE TITLE
Missing /home/deck/Emulation/tools/launchers/ryujinx.sh

### ISSUE THREAD

**Issue by c10l** [doZennn/steam-rom-manager#615]
On a clean Emudeck install, Ryujinx ROMs don't get parsed.

On the parser's settings I see the message `Executable is invalid!`:

<img width="995" alt="image" src="https://github.com/SteamGridDB/steam-rom-manager/assets/399431/c7542592-6a36-444c-9985-c1df2ce99ae3">

Upon inspection on that directory, the shell script is missing:

```shell
(1)(deck@deck ~)$ cd Emulation/tools/launchers/
(deck@deck launchers)$ ls -l
total 64
-rwxr-xr-x 1 deck deck 5031 Nov 28 18:27 cemu.sh
-rwxr-xr-x 1 deck deck  152 Nov 28 18:27 citra.sh
-rwxr-xr-x 1 deck deck  163 Nov 28 18:27 dolphin-emu.sh
-rwxr-xr-x 1 deck deck  196 Nov 28 18:27 duckstation.sh
-rwxr-xr-x 1 deck deck  157 Nov 28 18:27 melonds.sh
-rwxr-xr-x 1 deck deck  865 Nov 28 18:27 pcsx2-qt.sh
-rwxr-xr-x 1 deck deck  152 Nov 28 18:27 ppsspp.sh
-rwxr-xr-x 1 deck deck  168 Nov 28 18:27 primehack.sh
-rwxr-xr-x 1 deck deck  165 Nov 28 18:27 retroarch.sh
-rwxr-xr-x 1 deck deck  148 Nov 28 18:27 rpcs3.sh
-rwxr-xr-x 1 deck deck  156 Nov 28 18:27 scummvm.sh
-rwxr-xr-x 1 deck deck  458 Nov 28 18:27 vita3k.sh
-rwxr-xr-x 1 deck deck  144 Nov 28 18:27 xemu-emu.sh
-rwxr-xr-x 1 deck deck 6329 Nov 28 18:27 yuzu.sh
```

**Comment by fpiesche** [comment]
This is an EmuDeck problem so you should probably report that [over there](https://github.com/dragoonDorise/EmuDeck/).

**Comment by c10l** [comment]
Hey, thanks. Yeah sorry - I should have closed this issue before already. It was a botched EmuDeck install. Sorry for the noise!
