### ISSUE TITLE
Can’t get images for ROMs on SRM

### ISSUE THREAD

**Issue by Traiman36** [doZennn/steam-rom-manager#616]
I keep getting and error message everything I hit save to steam in SRM. The logs says what you see in the picture. 
Then when I scroll to the right the reason it gives is connect EACCESS 2606. Can anyone help. 

![IMG_8891](https://github.com/SteamGridDB/steam-rom-manager/assets/152780248/1848bb60-8efa-442f-adfd-489f6569ea59)

**Comment by kencinder** [comment]
This is a network issue, either on your end, or Steamgriddb at the time, not an actual problem with SRM. Closing
