### ISSUE TITLE
Steam Rom Manager cant find Ryujinx 

### ISSUE THREAD

**Issue by Retroboy85** [doZennn/steam-rom-manager#618]
I have no idea what has happened because everything was working perfectly fine since updating the emulator (flatpak).

I am not using Emudeck or anything like that, games used to play fine when adding to my Steam Library.

But now for some reason they wont play and when I check Steam Rom Manager its Emulator Directory looks strange and no matter how many times I alter it to where it should be, it keeps reverting back.

/var/lib/flatpak/exports/share/applications/org.ryjinx.desktop

I have even tried
/var/lib/flatpak/app/org.ryujinx.Ryujinx/x86_64/stable/23e56d2874c2060dbd73d38c2fc788d47ed761c3a39e28b08b5809f36beb112c/export/bin/

but it keeps changing to

/run/user/1000/doc/bunchofumbers

one thing I hate about the Steam Deck is how much hastle it is to pinpoint installation files, stupid that it simply does not create a shortcut like windows, it creates a copy and multiple versions.

I have also noticed other Emulators that were working perfectly fine are also showing invalid executable and having this user/1000/doc crap that wasnt like that before and only just noticed it, I cant find that directory either if I scan for it.

So I dont understand why all of a sudden Steam Rom manager is reverting to this random directory that I have never seen before, even if I try manually change the directory, it reverts back to it.

I am able to run the emulators then the games within the emulator perfectly fine, just Steam Rom manager for some reason is not allowing me to add games to my library and it boot that game up.

These seem to be FlatPak emulators, I have other emulators that I managed to copy its installation from my Steam Deck internal over to my SD CARD which I would prefer ALL of my EMULATORS to run off my SD CARD to avoid messing about having to configure everything again when upgrading the internal storage.

So for the likes of PS1/2/3, N64/NGC/GB/GBA all work perfectly fine still and Steam Rom manager has no issues with - because these I had figured out how to copy it over to my SD CARD and run it from there.

FlatPak emulators like Switch/3DS both have this same problem all of a sudden and will not let me set the executable directory - but if I run the emulators then the games they all work.

**Comment by kencinder** [comment]
Steam rom manager doesn't ship any emulators, or handle them in any way, it would make no changes or interact with your emulators.

**Comment by Retroboy85** [comment]
I dont use emudeck
________________________________

**Comment by Retroboy85** [comment]
> Steam rom manager doesn't ship any emulators, or handle them in any way, it would make no changes or interact with your emulators.

That is not even close to what I had posted.

I know Steam Rom Manager does not include Emulators or Roms, it is an app to let you point to where you have your emulators and roms stored onto your Steam Deck then add your Game Roms into your Steam Library as individual games, so you don't have to mess about opening up your Emulators, then select your Game Rom ever time.

It is very nice that it adds all of your individual Emulators Game Roms as if they were Steam Games in your Game Mode Library.

The issue I am trying to explain is that for some reason since doing updates to either Steam Deck, Steam Rom Manager or the Emulators, I cant pinpoint exactly which it would have been because all I know is that after doing the updates on the same day, that is when I noticed the issue.

I can state that this has only affected Emulators that are saved onto my Internal Storage, as for Emulators that I were able to extract and save to my SD Card and were able to boot from there rather than Internal Storage.

So as above, in Steam Rom Manager, when I manually try set the directory to its location where an Emulator is located on my Internal Storage, and then select it, it then takes me back to Steam Rom Manager (closes it pop up window to navigate to your directory) and it has automatically changed the directory I had set, to a directory that doesn't even exist.

As put above, I have given some examples of what the link will change to, for example this:
/run/user/1000/doc/

This directory doesn't even exist, it is NOT a directory that I have ever created nor can it be found if I try locate it.

When ever I manually locate my Emulator Directory and its executable, then add it to Steam Rom Manager, it keeps automatically changing itself.

I dont rely on the likes of EmuDeck where its kindof a lazy all in one thing and in some cases relies on RetroArch which tend to use outdated or inferior cores vs using individual emulators dedicated to that console itself and in most cases see that they have nightly updates.

So I prefer to manually download each emulator and have found those that I havent been able to figure out how to get it to install then export it to my SD Card rather than the Steam Decks stupid restriction to force everything to install to your Internal Storage (when in Desktop Mode).

If I am lucky to get it to run from my SD Card, then these Emulators are NOT affected in Steam Rom Manager.

I have noticed those that I am unable to boot from SD thus forced to run from Internal Storage are the ones for some reason have stopped working and keep changing the Directories that I set them to automatically.

Problem is, everything was working perfectly fine, I had my Steam Deck using Steam Rom Manager to manage all of my Emulators and Game Roms:
Nintendo GameBoy/GameBoy Color
Nintendo GameBoy Advance
Nintendo DS
Nintendo 3DS
Nintendo 64
Nintendo GameCube
###Nintendo Switch###
Sega MasterSystem
Sega MegaDrive
Sega 32X
Sega CD
Sega DreamCast
Sony PlayStation
Sony PlayStation 2
Sony PlayStation 3
Sony PlayStation Portable

The only one now I currently can NOT get to work from my SD Card and only run from my Internal Storage is ###Nintendo Switch### Ryujinx Flatpak. Bad enough that Steam Deck is a NIGHTMARE to locate the actual executable file as it always seems to create multiple versions including its Desktop Shortcuts, always seem to be a unique copy of the executable rather than been a simple shortcut like in Windows OS that will direct you to the ACTUAL executable file to which the Emulator has been installed to.

That has always been a NIGHTMARE for me to manually target the correct directories so I can then export it to my SD Card and UNINSTALL the Emulator from my Internal Storage and have it still run and continue running from my SD Card rather than Internal Storage.

Nintendo Switch thus far is the only one that I cannot figure out how to do it, It took me a while also with Citra 3DS where that after extracting the Emulators installation directory over to my SD Card, the Emulators will work, but after uninstalling it from my Internal Storage, for some reason the Extracted Emulator Directories on my SD Card will no longer work.

I know this part has nothing to do with Steam Rom Manager - just the issue for said Emulators that I am UNABLE to get to run from my SD Card and are restricted to running them from my Internal Storage. Any Emulator from my Internal Storage will not allow me to set the correct Emulator Executable Directory, after setting it, it automatically changes the Directory Path to something that doesn't even exist on my Internal Storage.

Sorry if this is a long post, I am finding it hard to try explain it clearly, I assumed first post was simple and clear, but I guess I came across and giving an impression that I was expecting Steam Rom Manager to be something to provide or handle emulators (which after reading first post, still believe it makes no comment of assuming or expecting Steam Rom Manager to be providing such a feature).

Ideally I want to continue figuring out how to get each and every single Emulator to be stored and run from my SD Card so that once they are all set up and configured, that's all done and dusted.

I intend on upgrading my Internal Storage (again) and when you have Emulators installed and running from your Internal Storage, it is STUPID that VALVE STILL have not given us users the option to select installations to the SD Card when in Desktop Mode.

This would make life hell of a lot easier, because each time I have had to upgrade my Internal Storage, I have had to mess about setting up all of my Emulators again and set up Steam Rom Manager each time.

So when I have it all running from my SD, regardless if I upgrade my Internal, It has no impact on my Steam Library and Steam Rom Manager as all I have to do is simply re create the same directories for any Game Roms that were set to my Internal Storage which is far EASIER to do, as all you need to do is connect via FTP and Drag/Drop my Game Roms over to my Internal Storage again and Steam Rom Manager doesn't even know anything has changed, other than my Steam Deck now knows it has a larger Internal Storage for more Games/Roms.

I've had to do this twice already now, default it came with 64GB, then upgraded to a 256GB then I plan on either going to a 1TB or wait to save for a 2TB SSD.

Again Sorry for a LONG post, I just have no clue what may have caused this issue to happen when I had previously been working perfectly fine. I don't get why it would automatically set a directory to something that isn't what I just set it to and that doesnt even exist at all on either Internal or SD Card.
