### ISSUE TITLE
unable to see all my steam games in the steam parser 

### ISSUE THREAD

**Issue by Cricket422** [doZennn/steam-rom-manager#622]
Hi, this is my first time writing one of these but I've been using steam rom manager on manjaro and I'm unable to see more than 3 games on my steam parser when I test it (I have way more than 3 in my library) it's in the right file format of my .steam folder on my desktop but it just doesn't seem to be able to find the games which is strange, had a strange issue where when testing it the parser would give me a error saying apps on the steam parser too but that seems to have gone away recently as of writing this 
![Screenshot from 2023-12-13 12-20-22](https://github.com/SteamGridDB/steam-rom-manager/assets/126555286/4175e93d-0c4c-4bfe-ab5e-14ce25d8de35)

**Comment by kencinder** [comment]
Read the information in SRM regarding the Steam parser, particularly `Limitations` under Parser Type info.

This isn't an issue that can currently be resolved and is a limitation caused by Steam.

**Comment by Cricket422** [comment]
ahhh thank you I'll look into this
