### ISSUE TITLE
Creating Or Editing A Custom Steam Game Category, Or Adding A Game To A Steam Category Removes All Games From Custom Categories

### ISSUE THREAD

**Issue by demonstrable** [doZennn/steam-rom-manager#624]
Hello, I'm having an issue on Windows 11 using SRM 2.4.17, when I add a game to a custom category, when I add a non-steam game to Steam, or when I edit/create a custom game category within Steam. Every time I make one of these changes, when I next close and relaunch Steam, all games are removed from custom categories but the game entry itself from SRM still exist. 

My issue seems very similar to the issue presented in this ticket: https://github.com/SteamGridDB/steam-rom-manager/issues/430

This category issue can occur when I make an edit myself or when I have added non-Steam games via the shortcut creator within Heroic Games Launcher.

Note, my Steam library has over 3,000 games, and I'm adding over 2,900 Roms to Steam via SRM. I am wondering if the size of the library has anything to do with it.

After Adding Games via SRM:
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/839146/167c6d04-68ce-4a2f-ad52-d658442af1a2)

After Adding A Non-Steam Game To Steam and Closing/Reopening Steam:
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/839146/17d8f107-aa14-43b0-b571-26b4a1614384)

**Comment by jenkshi** [comment]
I have the same issue

**Comment by cbartondock** [comment]
This is not an SRM issue it's a steam issue - once you have too many non steam games (around 1500) the categories become unstable in this way. It doesn't matter whether you used SRM to add the non steam games or not. I reported it to Valve a long time ago, alas no dice.
