### ISSUE TITLE
Add our own emulation parsers to Steam ROM Manager?

### ISSUE THREAD

**Issue by technohiker** [doZennn/steam-rom-manager#631]
I was looking to use Steam ROM Manager to add individual ROM entries to my Steam Deck for Gaming Mode.  However, the Parsers list doesn't seem to have any option to add any of our own emulators.  I was looking to use bSNES since I prefer that over snes9x.  Is this possible to set up in Steam ROM Manager?  I didn't see any option in there or Emudeck.

**Comment by kencinder** [comment]
A blank parser is present without selecting a preset as soon as SRM is opened it defaults to the "Create Parser" tab  or you can alter an existing preset to suit your needs.
If this isn't occurring for you, this would be an Emudeck issue you need to speak to them about.

Further assistance with making one can be found on the Discord
