### ISSUE TITLE
SRM causes certain games to launch using the x86 version under macOS instead of using the native arm version 

### ISSUE THREAD

**Issue by themacintoshnerd** [doZennn/steam-rom-manager#632]
On macOS many programs including emulators use fat binaries for distribution meaning they have code for multiple cpu architectures. Most of my emulators will launch their x86 versions using apple's rosetta when launching from steam on an arm host. The only exception was xemu which launched everything correctly. 

There is a workaround for this which is to use the [lipo command](urlhttps://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary) to remove the x86_64 code from the app but this is very much not ideal as it tends to get added back often which is especially annoying with emulators such as ryujinx that are updated nearly daily. I believe it can also cause issues with code signing but I would not know since I turned off checking code signatures on macOS. 

Hoping this can be fixed since this Mac mini is practically dying to be an emulation box.

**Comment by kencinder** [comment]
SRM doesn't *cause* anything to run a certain way, the executable\binary is run by Steam and that is all, nothing more.
SRM only creates a shortcut, absolutely nothing more than that.

This is not an SRM issue, if even possible it's a Steam issue.
