### ISSUE TITLE
Linux: Game won't launch (Steam Play button turns back to "Play" after about a second)

### ISSUE THREAD

**Issue by ReaderGuy42** [doZennn/steam-rom-manager#633]
I've gotten the game added to Steam but it won't launch. 
I've downloaded the correct Core DLC (as far as I can tell), but when I hit play it loads for a second and then doesn't do anything. And the button goes back to Play, so it never launches.

I'm guessing it has something to do with the core or Retroarch installation, but I can't tell what to do. In a video the person said to point the program at the executable (which in the video is a .exe file) but because I'm using a Linux (Mint) PC, I'm having a hard time figuring out which file to use for that.

Any ideas?
Thanks!

**Comment by kencinder** [comment]
Please use Discord for support. Github is for bugs etc, not individual support issues.
