### ISSUE TITLE
Add `-nogui` argument to PCSX2 preset

### ISSUE THREAD

**Issue by GrzegorzDyrda** [doZennn/steam-rom-manager#634]
## Current behaviour
Without `-nogui`, after you close the game, you still have to close the main PCSX2 window, which is not convenient.

## Expected behaviour
Adding `-nogui` fixes this issue. CLosing the game, closes the process, and returns to Steam.

## What needs to be done?
File: `files/presets/Sony PlayStation 2.json`
Line: `11`

Replace:
`"executableArgs": "\"${filePath}\" -fullscreen",`
with:
`"executableArgs": "\"${filePath}\" -nogui -fullscreen",`

**Comment by kencinder** [comment]
You are using an outdated version of PCSX2, see https://github.com/SteamGridDB/steam-rom-manager/issues/433
