### ISSUE TITLE
Crash and blank screen during "doing batch" step (with workaround)

### ISSUE THREAD

**Issue by XanderStrike** [doZennn/steam-rom-manager#636]
My ps1 and ps2 libraries both contain about 1400 games. The ps1 library adds to steam nearly instantly, but the ps2 library consistently hangs and then the whole application goes blank.

Since the app goes blank I can't view the logs to know what's happening, I didn't find any log files in the application folder.

### Steps:

Set up a PCSX2 configuration like in the screenshot below

Parse, wait for images to download

Click "save to steam"

Observe RAM usage climbs until (I assume) some critical process is OOM killed and the app becomes unresponsive, RAM usage falls. 

No shortcuts are added to steam.

<details>
<summary>
Screenshots (click me)
</summary>

![Screenshot 2024-03-01 081833](https://github.com/SteamGridDB/steam-rom-manager/assets/1565303/623f5fbb-8cc1-4136-a391-5c835c04853c)
![Screenshot 2024-03-01 081905](https://github.com/SteamGridDB/steam-rom-manager/assets/1565303/e3dcdb35-7b5a-4a3d-9833-1a7632b86f1c)

![Screenshot 2024-03-01 082841](https://github.com/SteamGridDB/steam-rom-manager/assets/1565303/96999f05-fc94-4d96-8d4f-62ea77c9063b)

</details>

### Workaround:

> [!WARNING]  
> This will wipe out all your shortcuts, including ones not added by SRM

This appears related to this closed but unresolved issue: https://github.com/SteamGridDB/steam-rom-manager/issues/589

Delete `shortcuts.vdf` and `addeditemsV2.json` in `<steam folder>/userdata/<userid>/config` 

Parse and save just PS2, it works (albeit very slowly) without consuming any additional RAM. 

### More Info

The fact that it reliably works for PS1 but not PS2 (except the first time) indicates that the issue is not with the size of the romset or its location (both are on a network drive). I can't see any differences in the configuration that aren't essential to the configuration's function, and I even put the flags back to the incorrect ones from the community config and it still didn't work. PS1 is using the DuckStation community config.

Since I want to manage all my shortcuts with SRM, it'd be cool if there was a setting to blow away `shortcuts.vdf` and `addeditemsV2.json` on save, rather than attempting to merge since the merging process is what seems to voraciously consume RAM. It wouldn't be a solution for everyone but it'd help some people I imagine.

SRM version: **2.4.17**
Operating System: **Windows 11**

**Comment by cbartondock** [comment]
This should be fixed in master, there was a massive amount of blocking code having to do with extraneous app Ids. Let me know if the next version of SRM still does this.
