### ISSUE TITLE
[BUG]Black screen when Parsing or Save to Steam.

### ISSUE THREAD

**Issue by phirephoto** [doZennn/steam-rom-manager#640]
When I select - depending on what emulator, either Parse, or Save to Steam, I'll get a black screen. Sometimes it's after a few seconds, sometimes a few minutes. Happens on almost all emulators. I don't see any log file, but would be happy to upload a log file if you can let me know what file would help.

It's a brand new Lenovo Legion GO. Latest Steam, latest SRM.

**Comment by DocMAX** [comment]
Same here

**Comment by cbartondock** [comment]
can you hit ctrl+shift+i to bring up the console and report if there are any errors? Maybe just take a screenshot.

**Comment by cbartondock** [comment]
Situation with save to steam should be improved by newest update.

**Comment by cbartondock** [comment]
This should be fixed afaik in 2.4.28. Let me know if it isn't and I will re-open.

**Comment by matata018** [comment]
Still happening.
