### ISSUE TITLE
[BUG]  I can't add the roms  > bug in the parse button

### ISSUE THREAD

**Issue by mappogos** [doZennn/steam-rom-manager#641]
This is my log

New config presets have been downloaded.
Todas as urls de imagem disponíveis foram recuperadas.
Executando analisadores.
Por favor, desligue o Steam se ele estiver em execução.
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.

![SRM bug](https://github.com/SteamGridDB/steam-rom-manager/assets/164449932/5294f1fb-57a5-40be-a6d1-4a5064a48d55)

**Comment by DonutEspresso** [comment]
@mappogos any chance you were using the stand alone version? I was able to replicate this bug with the stand alone version, but when using the exact same settings and parsers with the msi version, all seems to be working well.

**Comment by cbartondock** [comment]
Seek help on the discord, this is not a bug most likely but an incorrect configuration.
