### ISSUE TITLE
Fatal error occurred in preview. Windows 10 for PC

### ISSUE THREAD

**Issue by ipg95** [doZennn/steam-rom-manager#655]
i'm having this issue with my steam rom manager in emudeck "add your games to steam" step.

The error says: " Fatal error occurred in Preview. See event log for details. Error: ENOENT: no such file or directory, mkdir 'c:\program files (x86)\steam\userdata\155810593\config\grid'

i've already tried to delet this folder and open Steam to re-generate it, but it didnt work

![image](https://github.com/SteamGridDB/steam-rom-manager/assets/167698244/e8674073-394a-48c9-8af9-5c38c94b4d0d)

**Comment by cbartondock** [comment]
Fixed in 4.2.22
