### ISSUE TITLE
[REQUEST] Add support for Dualsense Edge in Steam ROM Manager

### ISSUE THREAD

**Issue by ghost** [doZennn/steam-rom-manager#656]
**Feature information**
Referring to the "Controller Templates Configuration" section in creating a parser, could support for the Dualsense Edge be added? 

**Additional context**

I don't personally own the controller but HHD (https://github.com/hhd-dev/hhd) is a wonderful software that emulates various portable handhelds on Linux as a Dualsense Edge. This allows for full controller support with gyro and back button configuration. 

Would benefit both people who own the controller and people who use HHD on Linux. 

In the VDF files, the Dualsense Edge is written as the following:

`controller_ps5_edge`

You can see the EmuDeck profile here: https://github.com/dragoonDorise/EmuDeck/blob/main/configs/steam-input/emudeck_controller_ps5_dualsense_edge.vdf

What additional information do you need from me?

**Comment by cbartondock** [comment]
Added in master.

**Comment by ghost** [comment]
Thank you :)
