### ISSUE TITLE
[REQUEST] Reword "Please shutdown Steam if it is running"

### ISSUE THREAD

**Issue by ghost** [doZennn/steam-rom-manager#657]
**Feature information**

If a user does not have a valid parser/valid ROMs/etc, then the only error Steam ROM Manager provides is "Please shutdown Steam if it is running" (if they are clicking the "Parse" button). This error can be confusing for new users especially if they have already confirmed Steam is closed. Beyond that, there's no singular way to troubleshoot what's happening. 

I'm not sure what the best solution here is though, but one suggestion is to reword the text to something like "No valid items or parsers found. X entries have been excluded." With X being a number pulled from the exclusions list. 

If a user excludes a ROM, the log doesn't clearly convey that. If there is an invalid parser, the rephrased error message could hint to the user, hey go check out the log.

The "Please shutdown Steam if it is running" message could be moved to the actual parser screen where you see "All available image urls retrieved." This could be reworded to "All available image urls retrieved. Please shutdown Steam if it is running before saving to Steam."

I don't think either of these are the perfect solution but I don't think the current error message is very helpful and tends to confuse new users.

**Comment by cbartondock** [comment]
That's not actually an error message, it's just information. SRM shows it no matter what. I agree it is confusing for people, probably what's needed is a separate message `Some parsers skipped for invalid configuration` or something like that, which does show up in the logs but isn't brought up as an alert.

**Comment by ghost** [comment]
Oh oops, then yes I think a separate message could work as well. I do see on occasion users excluding ROMs without realizing they've done so, but I'm not sure how exactly that happens so I'm not sure if that'd be helpful to include or not.

**Comment by cbartondock** [comment]
I've reworded it to "If steam is running, exit Steam". Hopefully that's clearer. I also added an info message "Enabled parsers returned no apps" in the case where no apps are returned.
