### ISSUE TITLE
Battle.net parser doesn't see Diablo IV or Diablo II

### ISSUE THREAD

**Issue by siriuslooker** [doZennn/steam-rom-manager#661]
- **Describe the bug**

Using the new battle.net parser template. I have 4 battle.net games installed per screenshot. (Diablo 4, Diablo 2, Diablo 3 and Starcraft 2)
When running or testing the parser it only picks up Diablo 3 and Starcraft 2.

- **Steps to reproduce the behavior**

Setup a new battle.net parser with the included template. Test the parser and note in the output that only 2 of 4 games were detected.

- **Expected behavior**

All 4 games should be detected.

- **Screenshots**

![image](https://github.com/SteamGridDB/steam-rom-manager/assets/6607211/45721188-33d2-44f6-9bd7-9ac704851e1e)
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/6607211/c85da289-ceec-4c83-bf87-eb6ed12f54c7)

**Comment by cbartondock** [comment]
This should be fixed in master, next update should have it.
