### ISSUE TITLE
[REQUEST] custom titles

### ISSUE THREAD

**Issue by BPplays** [doZennn/steam-rom-manager#662]
i would like the ability to change the displayed title of games.
for example if i have i game named 'どうぶつの森ｅ＋' and fix match to 'Doubutsu no Mori e+' the title changes to 'Doubutsu no Mori e+' and there is no way for me to have the association with the steamgriddb title and have it called 'どうぶつの森ｅ＋' it steam

**Comment by cbartondock** [comment]
This exists, you can just use the exception manager's "display title" field
