### ISSUE TITLE
[REQUEST] option to keep original title when fixing match

### ISSUE THREAD

**Issue by BPplays** [doZennn/steam-rom-manager#664]
if i have a game with a japanese title i don't want to change it to the english title when fixing a match, i know you can go into exceptions and change it back but i would like a toggle in the fix menu to change whether or not the title gets changed or stays the same.
also an option to change the name right in the fix menu would be useful too

**Comment by cbartondock** [comment]
This is a good idea, it will get added eventually.

**Comment by cbartondock** [comment]
Added in master.
