### ISSUE TITLE
[REQUEST] Let us see the file name of a game in the Parse page

### ISSUE THREAD

**Issue by Nayibmc** [doZennn/steam-rom-manager#665]
- **Feature information**
Please add a text that shows the name of the file for a ROM. Maybe even it's location. That would be it much easier to know what game it is if the Parser thinks it's a different game

- **Additional context**
For example, it could be next to the "Fix match for Halo 4" so it's like "Fix match for Halo 4 (Emulation/roms/xbox/Halo.iso)"
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/26173172/f768ec18-7fa7-4e18-9b01-d681250bdec9)

**Comment by cbartondock** [comment]
Added in 2.5.5
