### ISSUE TITLE
[BUG] No games on view games page even after adding to steam and refreshing

### ISSUE THREAD

**Issue by monyarm** [doZennn/steam-rom-manager#666]
- **Describe the bug**
The View Games page is empty. I went to Add Games, parsed and saved, then went to View Games and refreshed. But there was nothing there.

The last time I used SRM was version 2.4.17, so could this issue be due to some change between 2.4.17 and 2.4.29?

- **Steps to reproduce the behavior**
Add Games.
Go to View Games.
Refresh.
No games listed.

- **Expected behavior**
Add Games.
Go to View Games.
Refresh.
Some games listed.

- **Screenshots**
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/3044522/1170f34f-4638-4491-9f66-53b94469e755)

Other Info:
SRM says my OS is Linux 6.4 (I'm using Gentoo Linux)

**Comment by cbartondock** [comment]
Easy fix, will be in the next release.

**Comment by cbartondock** [comment]
Should be fixed in 2.5.5, let me know if not.
