### ISSUE TITLE
[REQUEST] Seperate file for user-defined customVariables

### ISSUE THREAD

**Issue by monyarm** [doZennn/steam-rom-manager#667]
- **Feature information**
Currently all Custom Variables are read from customVariables.json, but when updating to a new version of SRM, it sometimes overrides the file with an up to date one. Which wouldn't be an issue, if there was another file for user-defined custom variables. I use SRM for among other things Doom WADs, and using customVariables let's me do so without having to rename the files.

**Comment by cbartondock** [comment]
Good idea!

**Comment by cbartondock** [comment]
This will be in the next release.
