### ISSUE TITLE
[REQUEST] Parsing of GOG games installed directly instead of via GOG Galaxy

### ISSUE THREAD

**Issue by HazardousBackup** [doZennn/steam-rom-manager#672]
- **Feature information**

GOG provides for users to be able to download installers directly without using GOG Galaxy. So I suggest adding a parser or modifying the GOG parser to allow for parsing GOG games when GOG Galaxy is not installed.

- **Additional context**

As far as I can tell, all GOG games installed via their normal installers (possibly when installed via Galaxy as well) add a key to the registry on Windows (HKLM\SOFTWARE\WOW6432Node\GOG.com\Games) with all the information required to identify the game, it's path and other information.

I have a working test version in [my fork](https://github.com/HazardousBackup/steam-rom-manager/tree/Raw-GOG) I am not putting it as a pull request because I'm not confident my code is suitable for merging but I have successfully tested it on several titles.

**Comment by cbartondock** [comment]
If you submit a PR we can review it together. I would say it should be a setting in the Gog parser that appears on windows only, something like "use Registry instead of Galaxy DB"

**Comment by HazardousBackup** [comment]
@cbartondock I can look into it when I get the chance.

**Comment by cbartondock** [comment]
Added by your PR!
