### ISSUE TITLE
Fatal error occurred in preview (Flatpak SRM failing to follow symlinks)

### ISSUE THREAD

**Issue by DocMAX** [doZennn/steam-rom-manager#676]
![grafik](https://github.com/SteamGridDB/steam-rom-manager/assets/5351323/db206b1a-92d1-4025-b85a-6d4964e6fb88)

userdata a symlink to another local dir
also checked write permissions in flatpak
v2.5.9, (Bazzite OS, KDE flatpak)

**Comment by DocMAX** [comment]
Maybe it's because userdata is symlinked to a sshfs mountpoint? But that should be fixed on SRM side...

**Comment by cbartondock** [comment]
I am going to close this as I think this is more of a fundamental issue with flatpaks than it is with SRM.
