### ISSUE TITLE
[BUG] EA Desktop parser failed with fatal error: TypeError: Cannot read properties of undefined (reading 'tagName')

### ISSUE THREAD

**Issue by UnknownCyborgx** [doZennn/steam-rom-manager#677]
- **Describe the bug**
EA Desktop parser failed with fatal error: TypeError: Cannot read properties of undefined (reading 'tagName')

- **Expected behavior**
Working

**Comment by cbartondock** [comment]
Thanks! I will look into this.

**Comment by UnknownCyborgx** [comment]
> Thanks! I will look into this.

I have my games on my second harddrive. It still doesnt work.

**Comment by cbartondock** [comment]
This appears to be an upstream bug in fast-xml-parser. I'll let them know.

**Comment by cbartondock** [comment]
Possibly this https://github.com/NaturalIntelligence/fast-xml-parser/issues/620 (open) or this https://github.com/NaturalIntelligence/fast-xml-parser/issues/620 (closed, I just need to update the fast-xml-parser dependency).

Could you message me on Discord (lontanadascienza) and attach the following files:

`C:\Program Files (x86)\EA Games\*\__Installer\installerdata.xml` (the `*` is a wildcard, so I need this file from every subdirectory of EA Games that has it).

**Comment by UnknownCyborgx** [comment]
@cbartondock I sent you a friend request on discord.

**Comment by cbartondock** [comment]
Issue is fixed in master.

**Comment by andro23** [comment]
I am gettting this error using SRM 2.5.29 when trying to parse EA games stored on an external drive.
The app was able to parse all games stored on an internal drive without any issue.
