### ISSUE TITLE
[BUG] Adding to library via CLI stuck

### ISSUE THREAD

**Issue by DocMAX** [doZennn/steam-rom-manager#679]
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/5351323/19a1ada8-7c90-4ac6-9e2a-c2e3889f1e5f)
It always stuck here with one core 100% usage.
Latest version on linux (2.5.11)

**Comment by cbartondock** [comment]
I am unable to reproduce this, although that is an enormous number of apps to try to add at once. Did you try with a smaller number?

**Comment by cbartondock** [comment]
Closing for lack of response, I am still unable to reproduce.
