### ISSUE TITLE
Questions on start??

### ISSUE THREAD

**Issue by DocMAX** [doZennn/steam-rom-manager#680]
With you new version i get questions- Where is my steam dir in Linux. Is it /usr/bin/ or what? Or does it mean .local/share/Steam?!?
Why did you questions?!?!?

**Comment by cbartondock** [comment]
Next update will have a placeholder that tells you where it is, but it's `~/.steam/steam` typically. Basically, specifying the global steam directory is now mandatory as is global user accounts. Most of the errors I see are from people who didn't specify one or the other and have problems with an out of date steam account somewhere.
