### ISSUE TITLE
[REQUEST] On setup, should suggest steam directory for macOS

### ISSUE THREAD

**Issue by domdomegg** [doZennn/steam-rom-manager#682]
**Feature information**
It'd be great for SRM to automatically detect and suggest common locations for the Steam directory on macOS. Currently it only has a suggestion for where it might be on Windows.

By default on macOS it should be:

```ts
/Users/$USER/Library/Application Support/Steam
```

**Additional context**
![image](https://github.com/SteamGridDB/steam-rom-manager/assets/4953590/92806b53-0dd3-4eeb-8171-e0e5e55ccfbe)

**Comment by cbartondock** [comment]
Thanks for pointing this out! Was meant to already be this way but of course I forgot to actually add the system dependent stuff to the actual component template. Fixed (wil be in the next release)!
