### ISSUE TITLE
[BUG] Shortcut parser non-steam games do not work with Steam overlay

### ISSUE THREAD

**Issue by shawly** [doZennn/steam-rom-manager#685]
- **Describe the bug**

When using the shortcut parser the shortcuts are used as targets in the created non-steam games, the problem is that the Steam overlay will not work when a shortcut is used as non-steam game.

- **Steps to reproduce the behavior**

1. Create some shortcuts for games.
2. Scan the shortcuts with the Shortcut parser.
3. Run the created non-steam game
4. Try opening the ingame overlay

- **Expected behavior**

I expect the overlay to work but it seems to be a limitation of Steam itself.
This could be fixed by parsing the shortcuts target, arguments and working directory and creating a non-steam game from these properties.

I created a powershell script which does exactly this by creating manifest.json files from the shortcuts: https://gist.github.com/shawly/f301446b5e75639f642d76c114cd9446

I can use the Manual parser to parse these manifest.json files, but I'd rather have this functionality within the Shortcut parser.

- **Screenshots**

**Comment by cbartondock** [comment]
You can fix this by enabling shortcut passthrough in the parser, which parses the target instead (as you suggest).

**Comment by shawly** [comment]
Kind of yeah, it does not put arguments into launch options however, but putting them into the target seems to work okay I guess.

**Comment by cbartondock** [comment]
Do you have "append args to target" enabled? If not I am pretty sure it should set the launch options.

**Comment by shawly** [comment]
Neither enabling nor disabling that changes the result, the args are always appended to the target path.
