### ISSUE TITLE
[REQUEST] Upgrade electron beyond v24

### ISSUE THREAD

**Issue by xangelix** [doZennn/steam-rom-manager#687]
Electron v24 is getting quite old. Could this be bumped to something more recent?

**Comment by cbartondock** [comment]
Bumped to 31 in master. Also switched to yarn as a package manager in case that makes a difference for AUR.

**Comment by xangelix** [comment]
> Bumped to 31 in master. Also switched to yarn as a package manager in case that makes a difference for AUR.

Thanks so much Chris! I'll get the AUR-git version updated shortly :)
