### ISSUE TITLE
[BUG] First time turning on a game is very slow on the Deck, works fine after.

### ISSUE THREAD

**Issue by Emekcrash** [doZennn/steam-rom-manager#692]
- **Describe the bug**
 I just updated to the latest version and as soon as I did, every time I restart the steam deck, it takes around 2 minutes to run a game through the shortcuts steam rom manager makes. After the first time launching a game, it’s quick as it always was for every game. The game or emulator does not matter. When you press launch on any game, it simply stays blue, saying “Launching…” for a while. This happens every time I restart the deck.

I have tried resetting the configuration, reinstalling steam rom manager as well as reinstalling emu deck, and none of it worked.

- **Steps to reproduce the behavior**
 I simply updated steam rom manager and updated my game images. After the first long launch, restart steam deck for it to happen again.

- **Expected behavior**
 quick launch as usual

- **Screenshots**

**Comment by cbartondock** [comment]
It's not really possible that this is SRM's doing, as it is just adding shortcuts. The shortcuts haven't changed. It is almost certainly a coincidence that you updated SRM at the same time this happened. More likely this was caused by an emulator update (ifi you use emudeck you might have updated these at the same time) or a deck update.

**Comment by Emekcrash** [comment]
> It's not really possible that this is SRM's doing, as it is just adding shortcuts. The shortcuts haven't changed. It is almost certainly a coincidence that you updated SRM at the same time this happened. More likely this was caused by an emulator update (ifi you use emudeck you might have updated these at the same time) or a deck update.

Hey, yes it can't be as I was just changing the beta and stable client on the deck and the stable client doesn't have that problem, seems like the new steamos beta update did this (I added Firefox as a non steam game and had the same issue). Thanks for the reply and the great program.
