### ISSUE TITLE
[REQUEST] Launch Legendary games with Legendary

### ISSUE THREAD

**Issue by RuinTD** [doZennn/steam-rom-manager#700]
- **Feature information**
There should be an option in the Legendary parser to launch the game via Legendary.

- **Additional context**
This provides two benefits:
1. Allows the game to connect to Epic Online Services.
2. Allows Steam Game Recording (Beta) to record the game with EOS enabled. Game Recording doesn't work on the Epic parser (with "Launch games via Epic" turned on), possibly because it uses PowerShell to launch the game. (Tested with Fortnite on Windows 11)

**Comment by cbartondock** [comment]
Good call, added in master (it will be in the next release).

**Comment by RuinTD** [comment]
Hey, just wondering why I don't see this in master?

**Comment by cbartondock** [comment]
Because my push had failed for some reason :) it's in 2.5.22 now.
