### ISSUE TITLE
[REQUEST] Allow scraped grid images to be set to grid dimensions by default

### ISSUE THREAD

**Issue by anthonyajumelles** [doZennn/steam-rom-manager#703]
- **Feature information**
When scraping grid images for titles that have 512x512 or 1024x1024 options for either Capsule or Wide Capsule, it would be great to have a toggle in SRM's settings to only download those which fit the square dimensions.

- **Additional context**
SteamGridDB has finally worked out major kinks with allowing library grid images to be defaulted to square dimensions via the Decky plugin. This also allows for the most recent game in the Steam Big Picture mode carousel to be set to square.

**Comment by cbartondock** [comment]
Okay done in master!
